import Mathlib.Algebra.Group.End
import Mathlib.Data.Fintype.Basic
import Mathlib.Data.Quot
import Mathlib.GroupTheory.OrderOfElement
import KTLean.Axioms
import KTLean.Flux
import KTLean.Reversibility

/-!
# Closed Triflux

This module formalizes the primitive KT picture of three dynamical
flux states evolving under closure.

## Formal status

**Level 1 — Encoding and structural integration.**

This module combines existing formal structures:

- the three-state flux alphabet;
- unique triadic completion at the flux level;
- total reversible state evolution;
- realization of all three flux states.

No Fano plane, seven-path count, glyph count, octonionic dimension,
cosmological age, or physical constant is assumed here.

The intended interpretation is:

    triflux + reversible closure → persistent dynamical identity
-/

namespace ClosedTriflux

universe u

/--
A finite closed-triflux system.

`State` is the complete internal state space.

The system contains:

- total reversible dynamics;
- an observation of each complete state as one of the three flux states;
- a state-level completion operation whose observed value is exactly
  the canonical triadic completion;
- realization of every flux value by at least one complete state.

Finiteness will later allow reversible evolution to be decomposed into
closed dynamical orbits.
-/
structure System
    (State : Type u)
    [Fintype State] where

  /--
  Total reversible evolution of the complete state.
  -/
  dynamics :
    ReversibleStep State

  /--
  The flux value observed from a complete state.
  -/
  flux :
    State → Flux

  /--
  State-level completion of two complete states.
  -/
  complete :
    State → State → State

  /--
  State-level completion projects exactly to canonical triflux
  completion.
  -/
  flux_complete :
    ∀ left right : State,
      flux (complete left right) =
        triadicCompletion (flux left) (flux right)

  /--
  Every one of the three flux states is represented by at least one
  complete state.
  -/
  flux_surjective :
    Function.Surjective flux

/--
The reversible dynamics of a closed-triflux system determine a genuine
permutation of the complete state space.
-/
def System.stepEquiv
    {State : Type u}
    [Fintype State]
    (S : System State) :
    State ≃ State where

  toFun :=
    S.dynamics.step

  invFun :=
    S.dynamics.recover

  left_inv :=
    S.dynamics.recover_step

  right_inv :=
    S.dynamics.step_recover

@[simp]
theorem System.stepEquiv_apply
    {State : Type u}
    [Fintype State]
    (S : System State)
    (state : State) :
    S.stepEquiv state =
      S.dynamics.step state := by
  rfl

@[simp]
theorem System.stepEquiv_symm_apply
    {State : Type u}
    [Fintype State]
    (S : System State)
    (state : State) :
    S.stepEquiv.symm state =
      S.dynamics.recover state := by
  rfl

/--
A closed-triflux system has at least one complete state.

This follows constructively because the zero flux value must have a
representative.
-/
theorem System.state_nonempty
    {State : Type u}
    [Fintype State]
    (S : System State) :
    Nonempty State := by

  rcases S.flux_surjective Flux.zero with
    ⟨state, _⟩

  exact ⟨state⟩

/--
Every primitive flux value has a complete-state representative.
-/
theorem System.exists_state_with_flux
    {State : Type u}
    [Fintype State]
    (S : System State)
    (value : Flux) :
    ∃ state : State,
      S.flux state = value := by

  exact S.flux_surjective value

/--
Completion of complete states is observed as canonical triadic
completion.
-/
theorem System.observe_complete
    {State : Type u}
    [Fintype State]
    (S : System State)
    (left right : State) :
    S.flux (S.complete left right) =
      triadicCompletion
        (S.flux left)
        (S.flux right) := by

  exact S.flux_complete left right

/--
The local flux operation used by every closed-triflux system satisfies
KT Axiom 6.
-/
theorem System.local_triadicClosure
    {State : Type u}
    [Fintype State]
    (_S : System State) :
    TriadicClosure triadicCompletion := by

  exact completion_satisfies_axiom6

/--
Evolution of the complete state is bijective.

No complete-state information is destroyed by one dynamical step.
-/
theorem System.step_bijective
    {State : Type u}
    [Fintype State]
    (S : System State) :
    Function.Bijective S.dynamics.step := by

  exact
    ⟨
      ReversibleStep.step_injective S.dynamics,
      ReversibleStep.step_surjective S.dynamics
    ⟩

/--
The transition law generated by closed-triflux dynamics is total and
functional.
-/
theorem System.transition_totalFunctional
    {State : Type u}
    [Fintype State]
    (S : System State) :
    TotalFunctional
      (ReversibleStep.law S.dynamics) := by

  exact
    ReversibleStep.law_totalFunctional
      S.dynamics

end ClosedTriflux

#check ClosedTriflux.System
#check ClosedTriflux.System.stepEquiv
#check ClosedTriflux.System.state_nonempty
#check ClosedTriflux.System.local_triadicClosure
#check ClosedTriflux.System.step_bijective

namespace ClosedTriflux

universe u

/-!
## CT1: Dynamical orbit identity

A complete state may change under reversible evolution while remaining
part of the same closed dynamical identity.

Integer powers are used so that both forward and recovered motion are
included in one orbit relation.
-/

/--
Two complete states belong to the same dynamical orbit when one is
obtained from the other by an integer number of reversible steps.

Positive powers represent forward evolution.
Negative powers represent recovery.
Zero represents the unchanged state.
-/
def SameOrbit
    {State : Type u}
    [Fintype State]
    (S : System State)
    (left right : State) :
    Prop :=

  ∃ exponent : ℤ,
    (S.stepEquiv ^ exponent) left = right

/--
Every complete state belongs to its own orbit.
-/
theorem sameOrbit_refl
    {State : Type u}
    [Fintype State]
    (S : System State)
    (state : State) :
    SameOrbit S state state := by

  refine ⟨0, ?_⟩
  simp

/--
Dynamical orbit membership is symmetric because every forward motion
has a recovery motion.
-/
theorem sameOrbit_symm
    {State : Type u}
    [Fintype State]
    (S : System State)
    {left right : State}
    (h : SameOrbit S left right) :
    SameOrbit S right left := by

  rcases h with ⟨exponent, hexponent⟩
  subst right

  refine ⟨-exponent, ?_⟩

  rw [zpow_neg]

  exact
    (S.stepEquiv ^ exponent).symm_apply_apply left

/--
Dynamical orbit membership is transitive: successive pieces of motion
compose into one integer power of the reversible evolution.
-/
theorem sameOrbit_trans
    {State : Type u}
    [Fintype State]
    (S : System State)
    {first second third : State}
    (hfirst :
      SameOrbit S first second)
    (hsecond :
      SameOrbit S second third) :
    SameOrbit S first third := by

  rcases hfirst with
    ⟨firstExponent, hfirstExponent⟩

  rcases hsecond with
    ⟨secondExponent, hsecondExponent⟩

  refine
    ⟨secondExponent + firstExponent, ?_⟩

  rw [zpow_add]

  change
    (S.stepEquiv ^ secondExponent)
        ((S.stepEquiv ^ firstExponent) first) =
      third

  rw [
    hfirstExponent,
    hsecondExponent
  ]

/--
The reversible dynamical-orbit relation is an equivalence relation.
-/
theorem sameOrbit_equivalence
    {State : Type u}
    [Fintype State]
    (S : System State) :
    Equivalence (SameOrbit S) :=

  ⟨
    sameOrbit_refl S,
    by
      intro left right h
      exact sameOrbit_symm S h,
    by
      intro first second third hfirst hsecond
      exact
        sameOrbit_trans
          S
          hfirst
          hsecond
  ⟩

/--
The setoid of complete states identified by reversible dynamical
motion.
-/
def orbitSetoid
    {State : Type u}
    [Fintype State]
    (S : System State) :
    Setoid State where

  r :=
    SameOrbit S

  iseqv :=
    sameOrbit_equivalence S

/--
A dynamically persistent reality is an orbit class of complete states.

The internal complete state may change, but all states connected by
reversible evolution represent the same dynamical identity.
-/
abbrev Reality
    {State : Type u}
    [Fintype State]
    (S : System State) :=
  Quotient (orbitSetoid S)

/--
The persistent reality represented by one complete internal state.
-/
def realityOf
    {State : Type u}
    [Fintype State]
    (S : System State)
    (state : State) :
    Reality S :=

  Quotient.mk
    (orbitSetoid S)
    state

/--
A single forward step remains within the same dynamical orbit.
-/
theorem sameOrbit_step
    {State : Type u}
    [Fintype State]
    (S : System State)
    (state : State) :
    SameOrbit
      S
      state
      (S.dynamics.step state) := by

  refine ⟨1, ?_⟩

  change
    S.stepEquiv state =
      S.dynamics.step state

  exact S.stepEquiv_apply state
/--
Motion changes the complete internal state but preserves its persistent
reality class.

This is the first formal closed-triflux persistence theorem.
-/
theorem realityOf_step
    {State : Type u}
    [Fintype State]
    (S : System State)
    (state : State) :
    realityOf S (S.dynamics.step state) =
      realityOf S state := by

  apply Quotient.sound

  exact
    sameOrbit_symm
      S
      (sameOrbit_step S state)

/--
Orbit-equivalent complete states determine the same persistent reality.
-/
theorem realityOf_eq_of_sameOrbit
    {State : Type u}
    [Fintype State]
    (S : System State)
    {left right : State}
    (h : SameOrbit S left right) :
    realityOf S left =
      realityOf S right := by

  exact Quotient.sound h

/--
Two complete states represent the same persistent reality exactly when
they belong to the same reversible dynamical orbit.
-/
theorem realityOf_eq_iff
    {State : Type u}
    [Fintype State]
    (S : System State)
    {left right : State} :
    realityOf S left =
        realityOf S right
      ↔
    SameOrbit S left right := by

  constructor

  · intro h
    exact Quotient.exact h

  · intro h
    exact realityOf_eq_of_sameOrbit S h

/--
Every closed-triflux system generates at least one persistent reality.
-/
theorem reality_nonempty
    {State : Type u}
    [Fintype State]
    (S : System State) :
    Nonempty (Reality S) := by

  rcases S.state_nonempty with
    ⟨state⟩

  exact
    ⟨realityOf S state⟩

end ClosedTriflux

#check ClosedTriflux.SameOrbit
#check ClosedTriflux.Reality
#check ClosedTriflux.realityOf_step
#check ClosedTriflux.realityOf_eq_iff
#check ClosedTriflux.reality_nonempty

namespace ClosedTriflux

universe u

/-!
## CT2: Literal periodic closure

Because the complete state space is finite and evolution is reversible,
the dynamical permutation has finite positive order.

Consequently every complete state returns exactly after one common
global period.
-/

/--
The global period of a closed-triflux system is the group-theoretic
order of its reversible state permutation.
-/
noncomputable def System.globalPeriod
    {State : Type u}
    [Fintype State]
    (S : System State) :
    ℕ :=
  orderOf S.stepEquiv

/--
The global period is strictly positive.
-/
theorem System.globalPeriod_pos
    {State : Type u}
    [Fintype State]
    (S : System State) :
    0 < S.globalPeriod := by

  classical

  unfold globalPeriod

  exact orderOf_pos S.stepEquiv

/--
After one global period, the complete-state permutation is exactly the
identity permutation.
-/
theorem System.stepEquiv_pow_globalPeriod
    {State : Type u}
    [Fintype State]
    (S : System State) :
    S.stepEquiv ^ S.globalPeriod =
      1 := by

  classical

  unfold globalPeriod

  exact pow_orderOf_eq_one S.stepEquiv

/--
Every complete state returns to itself after the same positive global
period.

This is the literal finite reversible-closure theorem.
-/
theorem System.state_returns_after_globalPeriod
    {State : Type u}
    [Fintype State]
    (S : System State)
    (state : State) :
    (S.stepEquiv ^ S.globalPeriod) state =
      state := by

  rw [S.stepEquiv_pow_globalPeriod]

  rfl

/--
Every complete state has some strictly positive return time.
-/
theorem System.exists_positive_return
    {State : Type u}
    [Fintype State]
    (S : System State)
    (state : State) :
    ∃ period : ℕ,
      0 < period ∧
      (S.stepEquiv ^ period) state = state := by

  exact
    ⟨
      S.globalPeriod,
      S.globalPeriod_pos,
      S.state_returns_after_globalPeriod state
    ⟩

/--
The state reached after one global period represents the same reality,
because it is in fact the identical complete state.
-/
theorem System.reality_closes_after_globalPeriod
    {State : Type u}
    [Fintype State]
    (S : System State)
    (state : State) :
    realityOf S
        ((S.stepEquiv ^ S.globalPeriod) state) =
      realityOf S state := by

  rw [S.state_returns_after_globalPeriod]

end ClosedTriflux

#check ClosedTriflux.System.globalPeriod
#check ClosedTriflux.System.globalPeriod_pos
#check ClosedTriflux.System.state_returns_after_globalPeriod
#check ClosedTriflux.System.exists_positive_return
#check ClosedTriflux.System.reality_closes_after_globalPeriod

namespace ClosedTriflux

universe u

/-!
## CT3: One connected reality

Periodic reversible dynamics may decompose into several disconnected
orbits. Each orbit is a persistent reality in the sense defined above.

This section isolates the stronger condition under which every complete
state belongs to one common orbit. Under that condition, the reality
quotient contains exactly one element.

No path count, Fano structure, glyph count, or cosmological parameter
is assumed.
-/

/--
A closed-triflux system is orbit-connected when every complete state
can be reached from every other complete state by an integer number of
forward or recovery steps.

Equivalently, the reversible state permutation consists of one orbit.
-/
def OrbitConnected
    {State : Type u}
    [Fintype State]
    (S : System State) :
    Prop :=

  ∀ left right : State,
    SameOrbit S left right

/--
Orbit connectedness is equivalent to all complete states representing
the same persistent reality.
-/
theorem orbitConnected_iff_realityOf_eq
    {State : Type u}
    [Fintype State]
    (S : System State) :
    OrbitConnected S
      ↔
    ∀ left right : State,
      realityOf S left =
        realityOf S right := by

  constructor

  · intro hConnected left right

    exact
      realityOf_eq_of_sameOrbit
        S
        (hConnected left right)

  · intro hReality left right

    exact
      (realityOf_eq_iff S).1
        (hReality left right)

/--
If every complete state belongs to one orbit, then the reality quotient
is a subsingleton: any two persistent realities are equal.
-/
theorem reality_subsingleton_of_orbitConnected
    {State : Type u}
    [Fintype State]
    (S : System State)
    (hConnected : OrbitConnected S) :
    Subsingleton (Reality S) where

  allEq := by
    intro leftReality rightReality

    refine
      Quotient.inductionOn₂
        leftReality
        rightReality
        ?_

    intro left right

    exact
      Quotient.sound
        (hConnected left right)

/--
Conversely, if the reality quotient is a subsingleton, then every
complete state lies in one common orbit.
-/
theorem orbitConnected_of_reality_subsingleton
    {State : Type u}
    [Fintype State]
    (S : System State)
    (hReality :
      Subsingleton (Reality S)) :
    OrbitConnected S := by

  intro left right

  apply
    (realityOf_eq_iff S).1

  exact
    hReality.allEq
      (realityOf S left)
      (realityOf S right)

/--
A closed-triflux system is orbit-connected exactly when its persistent
reality space has at most one element.
-/
theorem orbitConnected_iff_reality_subsingleton
    {State : Type u}
    [Fintype State]
    (S : System State) :
    OrbitConnected S
      ↔
    Subsingleton (Reality S) := by

  constructor

  · exact
      reality_subsingleton_of_orbitConnected
        S

  · exact
      orbitConnected_of_reality_subsingleton
        S

/--
Under orbit connectedness, all complete internal states represent one
and the same persistent reality.
-/
theorem all_states_same_reality_of_orbitConnected
    {State : Type u}
    [Fintype State]
    (S : System State)
    (hConnected : OrbitConnected S)
    (left right : State) :
    realityOf S left =
      realityOf S right := by

  exact
    (orbitConnected_iff_realityOf_eq S).1
      hConnected
      left
      right

/--
An orbit-connected closed-triflux system generates exactly one
persistent reality.

Existence follows from realization of the three flux states.
Uniqueness follows from orbit connectedness.
-/
theorem existsUnique_reality_of_orbitConnected
    {State : Type u}
    [Fintype State]
    (S : System State)
    (hConnected : OrbitConnected S) :
    ∃! reality : Reality S,
      True := by

  rcases reality_nonempty S with
    ⟨reality⟩

  refine
    ⟨
      reality,
      trivial,
      ?_
    ⟩

  intro candidate _

  exact
    (reality_subsingleton_of_orbitConnected
      S
      hConnected).allEq
        candidate
        reality

end ClosedTriflux

#check ClosedTriflux.OrbitConnected
#check ClosedTriflux.orbitConnected_iff_realityOf_eq
#check ClosedTriflux.orbitConnected_iff_reality_subsingleton
#check ClosedTriflux.all_states_same_reality_of_orbitConnected
#check ClosedTriflux.existsUnique_reality_of_orbitConnected
