import Mathlib.Data.Fintype.Basic
import Mathlib.Data.Fintype.Basic
import KTLean.Axioms
import KTLean.Reversibility

/-!
# Closed Triflux

This module formalizes the primitive KT picture of three dynamical
flux states evolving under closure.

## Formal status

**Level 1 — Encoding and structural integration.**

This module combines existing formal structures:

- the three-state flux alphabet;
- unique triadic completion at the flux level;
- total reversible state evolution;
- realization of all three flux states.

No Fano plane, seven-path count, glyph count, octonionic dimension,
cosmological age, or physical constant is assumed here.

The intended interpretation is:

    triflux + reversible closure → persistent dynamical identity
-/

namespace ClosedTriflux

universe u

/--
A finite closed-triflux system.

`State` is the complete internal state space.

The system contains:

- total reversible dynamics;
- an observation of each complete state as one of the three flux states;
- a state-level completion operation whose observed value is exactly
  the canonical triadic completion;
- realization of every flux value by at least one complete state.

Finiteness will later allow reversible evolution to be decomposed into
closed dynamical orbits.
-/
structure System
    (State : Type u)
    [Fintype State] where

  /--
  Total reversible evolution of the complete state.
  -/
  dynamics :
    ReversibleStep State

  /--
  The flux value observed from a complete state.
  -/
  flux :
    State → Flux

  /--
  State-level completion of two complete states.
  -/
  complete :
    State → State → State

  /--
  State-level completion projects exactly to canonical triflux
  completion.
  -/
  flux_complete :
    ∀ left right : State,
      flux (complete left right) =
        triadicCompletion (flux left) (flux right)

  /--
  Every one of the three flux states is represented by at least one
  complete state.
  -/
  flux_surjective :
    Function.Surjective flux

/--
The reversible dynamics of a closed-triflux system determine a genuine
permutation of the complete state space.
-/
def System.stepEquiv
    {State : Type u}
    [Fintype State]
    (S : System State) :
    State ≃ State where

  toFun :=
    S.dynamics.step

  invFun :=
    S.dynamics.recover

  left_inv :=
    S.dynamics.recover_step

  right_inv :=
    S.dynamics.step_recover

@[simp]
theorem System.stepEquiv_apply
    {State : Type u}
    [Fintype State]
    (S : System State)
    (state : State) :
    S.stepEquiv state =
      S.dynamics.step state := by
  rfl

@[simp]
theorem System.stepEquiv_symm_apply
    {State : Type u}
    [Fintype State]
    (S : System State)
    (state : State) :
    S.stepEquiv.symm state =
      S.dynamics.recover state := by
  rfl

/--
A closed-triflux system has at least one complete state.

This follows constructively because the zero flux value must have a
representative.
-/
theorem System.state_nonempty
    {State : Type u}
    [Fintype State]
    (S : System State) :
    Nonempty State := by

  rcases S.flux_surjective Flux.zero with
    ⟨state, _⟩

  exact ⟨state⟩

/--
Every primitive flux value has a complete-state representative.
-/
theorem System.exists_state_with_flux
    {State : Type u}
    [Fintype State]
    (S : System State)
    (value : Flux) :
    ∃ state : State,
      S.flux state = value := by

  exact S.flux_surjective value

/--
Completion of complete states is observed as canonical triadic
completion.
-/
theorem System.observe_complete
    {State : Type u}
    [Fintype State]
    (S : System State)
    (left right : State) :
    S.flux (S.complete left right) =
      triadicCompletion
        (S.flux left)
        (S.flux right) := by

  exact S.flux_complete left right

/--
The local flux operation used by every closed-triflux system satisfies
KT Axiom 6.
-/
theorem System.local_triadicClosure
    {State : Type u}
    [Fintype State]
    (_S : System State) :
    TriadicClosure triadicCompletion := by

  exact completion_satisfies_axiom6

/--
Evolution of the complete state is bijective.

No complete-state information is destroyed by one dynamical step.
-/
theorem System.step_bijective
    {State : Type u}
    [Fintype State]
    (S : System State) :
    Function.Bijective S.dynamics.step := by

  exact
    ⟨
      ReversibleStep.step_injective S.dynamics,
      ReversibleStep.step_surjective S.dynamics
    ⟩

/--
The transition law generated by closed-triflux dynamics is total and
functional.
-/
theorem System.transition_totalFunctional
    {State : Type u}
    [Fintype State]
    (S : System State) :
    TotalFunctional
      (ReversibleStep.law S.dynamics) := by

  exact
    ReversibleStep.law_totalFunctional
      S.dynamics

end ClosedTriflux

#check ClosedTriflux.System
#check ClosedTriflux.System.stepEquiv
#check ClosedTriflux.System.state_nonempty
#check ClosedTriflux.System.local_triadicClosure
#check ClosedTriflux.System.step_bijective
