import KTLean.Composition
import KTLean.MemoryEscrow

/-!
# Composition Algebra and Reversibility

A nonzero element of a finite-dimensional composition algebra
with anisotropic multiplicative norm-square induces a reversible
state transformation by left multiplication.

Forward evolution is multiplication by the selected element.

Recovery is supplied by the inverse linear equivalence.

This construction is deliberately marked `noncomputable`:
finite-dimensional bijectivity proves that the inverse exists,
but does not yet provide the explicit algebraic inverse formula
that later quaternion and octonion constructions will supply.
-/

universe u v


namespace CompositionCore


/--
Left multiplication by a nonzero element, packaged as a
general reversible state transition.

Forward evolution is multiplication by `a`.

Recovery is the inverse linear equivalence supplied by
finite-dimensionality.
-/
noncomputable def leftMulReversibleStep
    {K : Type u}
    {A : Type v}
    [Field K]
    [NonAssocRing A]
    [Module K A]
    [SMulCommClass K A A]
    [IsScalarTower K A A]
    [FiniteDimensional K A]
    (C : CompositionCore K A)
    (hAniso : QuadraticMap.Anisotropic C.normSq)
    {a : A}
    (ha : a ≠ 0) :
    ReversibleStep A where

  step := fun x => a * x

  recover :=
    (C.leftMulEquiv hAniso ha).symm

  recover_step := by
    intro x
    exact C.leftMulEquiv_recovers hAniso ha x

  step_recover := by
    intro target
    exact C.leftMulEquiv_reconstructs hAniso ha target


/--
The forward operation carried by the reversible structure
is left multiplication by `a`.
-/
@[simp]
theorem leftMulReversibleStep_step
    {K : Type u}
    {A : Type v}
    [Field K]
    [NonAssocRing A]
    [Module K A]
    [SMulCommClass K A A]
    [IsScalarTower K A A]
    [FiniteDimensional K A]
    (C : CompositionCore K A)
    (hAniso : QuadraticMap.Anisotropic C.normSq)
    {a : A}
    (ha : a ≠ 0)
    (x : A) :
    (C.leftMulReversibleStep hAniso ha).step x =
      a * x := by

  rfl


/--
The recovery operation is the inverse linear equivalence.
-/
@[simp]
theorem leftMulReversibleStep_recover
    {K : Type u}
    {A : Type v}
    [Field K]
    [NonAssocRing A]
    [Module K A]
    [SMulCommClass K A A]
    [IsScalarTower K A A]
    [FiniteDimensional K A]
    (C : CompositionCore K A)
    (hAniso : QuadraticMap.Anisotropic C.normSq)
    {a : A}
    (ha : a ≠ 0)
    (x : A) :
    (C.leftMulReversibleStep hAniso ha).recover x =
      (C.leftMulEquiv hAniso ha).symm x := by

  rfl


/--
The Peano-indexed history generated by repeated
left multiplication by `a`.
-/
noncomputable def leftMulHistory
    {K : Type u}
    {A : Type v}
    [Field K]
    [NonAssocRing A]
    [Module K A]
    [SMulCommClass K A A]
    [IsScalarTower K A A]
    [FiniteDimensional K A]
    (C : CompositionCore K A)
    (hAniso : QuadraticMap.Anisotropic C.normSq)
    {a : A}
    (ha : a ≠ 0)
    (initial : A) :
    Nat → A :=

  ReversibleStep.history
    (C.leftMulReversibleStep hAniso ha)
    initial


/--
Each successor state is produced by multiplication
on the left by `a`.
-/
@[simp]
theorem leftMulHistory_succ
    {K : Type u}
    {A : Type v}
    [Field K]
    [NonAssocRing A]
    [Module K A]
    [SMulCommClass K A A]
    [IsScalarTower K A A]
    [FiniteDimensional K A]
    (C : CompositionCore K A)
    (hAniso : QuadraticMap.Anisotropic C.normSq)
    {a : A}
    (ha : a ≠ 0)
    (initial : A)
    (n : Nat) :
    C.leftMulHistory hAniso ha initial (Nat.succ n) =
      a * C.leftMulHistory hAniso ha initial n := by

  rfl


/--
The immediately preceding state is recoverable from
the following state.
-/
theorem leftMulHistory_recovers_previous
    {K : Type u}
    {A : Type v}
    [Field K]
    [NonAssocRing A]
    [Module K A]
    [SMulCommClass K A A]
    [IsScalarTower K A A]
    [FiniteDimensional K A]
    (C : CompositionCore K A)
    (hAniso : QuadraticMap.Anisotropic C.normSq)
    {a : A}
    (ha : a ≠ 0)
    (initial : A)
    (n : Nat) :
    (C.leftMulReversibleStep hAniso ha).recover
        (C.leftMulHistory hAniso ha initial (Nat.succ n)) =
      C.leftMulHistory hAniso ha initial n := by

  simpa [leftMulHistory] using
    ReversibleStep.history_recovers_previous
      (C.leftMulReversibleStep hAniso ha)
      initial
      n


/--
Any state `k` steps in the past can be recovered by
applying the recovery operation `k` times.

This is finite-depth memory escrow for multiplication
in a composition algebra.
-/
theorem leftMulHistory_recovers_after
    {K : Type u}
    {A : Type v}
    [Field K]
    [NonAssocRing A]
    [Module K A]
    [SMulCommClass K A A]
    [IsScalarTower K A A]
    [FiniteDimensional K A]
    (C : CompositionCore K A)
    (hAniso : QuadraticMap.Anisotropic C.normSq)
    {a : A}
    (ha : a ≠ 0)
    (initial : A)
    (n k : Nat) :
    ReversibleStep.recoverN
        (C.leftMulReversibleStep hAniso ha)
        k
        (C.leftMulHistory hAniso ha initial (n + k)) =
      C.leftMulHistory hAniso ha initial n := by

  simpa [leftMulHistory] using
    ReversibleStep.history_recovers_after
      (C.leftMulReversibleStep hAniso ha)
      initial
      n
      k


end CompositionCore


#check CompositionCore.leftMulReversibleStep
#check CompositionCore.leftMulReversibleStep_step
#check CompositionCore.leftMulReversibleStep_recover
#check CompositionCore.leftMulHistory
#check CompositionCore.leftMulHistory_succ
#check CompositionCore.leftMulHistory_recovers_previous
#check CompositionCore.leftMulHistory_recovers_after
