import KTLean.Axioms

/-!
Peano-indexed evolution and state history in Kosmoplex Theory.
-/

universe u


/--
The ordered history generated by repeatedly applying a total
state-transition function.

The natural number indexes the record:

* `0` records the initial state.
* `Nat.succ n` records one further lawful transformation.
-/
def stateHistory {State : Type u}
    (step : State → State)
    (initial : State) :
    Nat → State
  | 0 => initial
  | Nat.succ n =>
      step (stateHistory step initial n)


@[simp]
theorem stateHistory_zero
    {State : Type u}
    (step : State → State)
    (initial : State) :
    stateHistory step initial 0 = initial := by
  rfl


@[simp]
theorem stateHistory_succ
    {State : Type u}
    (step : State → State)
    (initial : State)
    (n : Nat) :
    stateHistory step initial (Nat.succ n) =
      step (stateHistory step initial n) := by
  rfl


/--
A realized history is the Peano-indexed record generated
by the total function carried by a realization.
-/
def realizedHistory
    {State : Type u}
    {law : TransitionLaw State}
    (realization : Realization law)
    (initial : State) :
    Nat → State :=
  stateHistory realization.step initial


/--
Every adjacent pair of states in a realized history
satisfies the transition law.

The record therefore contains no undefined transition.
-/
theorem realizedHistory_respects_law
    {State : Type u}
    {law : TransitionLaw State}
    (realization : Realization law)
    (initial : State)
    (n : Nat) :
    law
      (realizedHistory realization initial n)
      (realizedHistory realization initial (Nat.succ n)) := by
  change law
    (stateHistory realization.step initial n)
    (realization.step
      (stateHistory realization.step initial n))

  exact
    (realization.realizes
      (stateHistory realization.step initial n)
      (realization.step
        (stateHistory realization.step initial n))).2 rfl


#check stateHistory
#check stateHistory_zero
#check stateHistory_succ
#check realizedHistory
#check realizedHistory_respects_law


/--
Any history with the same initial state and the same
successor rule is identical to `stateHistory`.

Thus an initial state and a total transition function
determine exactly one Peano-indexed record.
-/
theorem stateHistory_unique
    {State : Type u}
    (step : State → State)
    (initial : State)
    (history : Nat → State)
    (hzero : history 0 = initial)
    (hsucc : ∀ n : Nat,
      history (Nat.succ n) = step (history n)) :
    history = stateHistory step initial := by
  funext n
  induction n with
  | zero =>
      exact hzero
  | succ n ih =>
      rw [hsucc n, stateHistory_succ, ih]


/--
A realization and an initial state determine exactly
one lawful Peano-indexed history.
-/
theorem realizedHistory_unique
    {State : Type u}
    {law : TransitionLaw State}
    (realization : Realization law)
    (initial : State)
    (history : Nat → State)
    (hzero : history 0 = initial)
    (hsucc : ∀ n : Nat,
      history (Nat.succ n) =
        realization.step (history n)) :
    history = realizedHistory realization initial := by
  exact stateHistory_unique
    realization.step
    initial
    history
    hzero
    hsucc


#check stateHistory_unique
#check realizedHistory_unique
