import KTLean.FanoAutomorphism
import KTLean.FanoFrame

/-!
# Fano automorphisms acting on ordered frames

This module begins the structural bridge between the two
independently established 168-element types:

* the intrinsic automorphism group of the Fano completion law;
* the ordered noncollinear frames of the Fano plane.

A fixed reference frame is chosen. Every Fano automorphism
sends that frame to another valid frame.

Later modules will prove that this evaluation map is injective
and then bijective.
-/

namespace FanoAutomorphismFrame

/--
The ordered triple `(0,1,2)` is a noncollinear Fano frame.

The line generated by `0` and `1` is `{0,1,3}`, so `2`
lies outside it.
-/
def referenceFrame :
    FanoFrame.Frame :=
  ⟨(0, 1, 2), by
    native_decide⟩

/--
A Fano automorphism preserves membership in every generated
Fano block.
-/
theorem map_mem_block_iff
    (σ : FanoAutomorphism.Automorphism)
    (x y z : Fano.Point) :
    σ.1 z ∈
        Fano.system.block
          (σ.1 x)
          (σ.1 y) ↔
      z ∈ Fano.system.block x y := by
  have hmap :
      σ.1 (Fano.system.complete x y) =
        Fano.system.complete (σ.1 x) (σ.1 y) := by
    simpa [Fano.system] using
      FanoAutomorphism.map_complete σ x y

  simp [Steiner.TripleSystem.block]
  constructor
  · intro h
    rcases h with h | h | h
    · exact Or.inl h
    · exact Or.inr (Or.inl h)
    · exact Or.inr (Or.inr (
        σ.1.injective (by
          calc
            σ.1 z = Fano.system.complete (σ.1 x) (σ.1 y) := h
            _ = σ.1 (Fano.system.complete x y) := by
              symm
              exact hmap)))
  · intro h
    rcases h with h | h | h
    · exact Or.inl h
    · exact Or.inr (Or.inl h)
    · exact Or.inr (Or.inr (by
        rw [h]
        exact hmap))

/--
The image of the reference frame under a Fano automorphism
is again an ordered noncollinear frame.
-/
def imageFrame
    (σ : FanoAutomorphism.Automorphism) :
    FanoFrame.Frame :=
  ⟨
    (σ.1 0, σ.1 1, σ.1 2),
    by
      constructor

      · intro h
        have h' : (0 : Fano.Point) = 1 :=
          σ.1.injective h
        exact (by decide : (0 : Fano.Point) ≠ 1) h'

      · intro h

        have h' :
            (2 : Fano.Point) ∈
              Fano.system.block
                (0 : Fano.Point)
                (1 : Fano.Point) :=
          (map_mem_block_iff
            σ
            0
            1
            2).mp h

        exact
          referenceFrame.2.2 h'
  ⟩

/--
The first point of the image frame is the image of `0`.
-/
@[simp]
theorem imageFrame_first
    (σ : FanoAutomorphism.Automorphism) :
    FanoFrame.first (imageFrame σ) =
      σ.1 0 := by
  rfl

/--
The second point of the image frame is the image of `1`.
-/
@[simp]
theorem imageFrame_second
    (σ : FanoAutomorphism.Automorphism) :
    FanoFrame.second (imageFrame σ) =
      σ.1 1 := by
  rfl

/--
The third point of the image frame is the image of `2`.
-/
@[simp]
theorem imageFrame_third
    (σ : FanoAutomorphism.Automorphism) :
    FanoFrame.third (imageFrame σ) =
      σ.1 2 := by
  rfl

end FanoAutomorphismFrame
