import KTLean.Fano
import Mathlib.Data.Fintype.Card
import Mathlib.Data.Fintype.Prod

/-!
# Ordered noncollinear frames of the Fano plane

An ordered Fano frame consists of three points `(x,y,z)` such that

* `x` and `y` are distinct, and
* `z` does not lie on the Fano line generated by `x` and `y`.

There are seven choices for `x`, six remaining choices for `y`,
and four points outside the line generated by that ordered pair.

Hence the set of ordered noncollinear Fano frames has cardinality

    7 × 6 × 4 = 168.

This gives the structural finite object that will later be shown
equivalent to the intrinsic Fano automorphism group.
-/

namespace FanoFrame

/--
A raw ordered triple of Fano points.
-/
abbrev RawFrame :=
  Fano.Point × Fano.Point × Fano.Point

/--
A raw triple `(x,y,z)` is a Fano frame when `x ≠ y`
and `z` lies outside the block generated by `x` and `y`.
-/
def IsFrame
    (t : RawFrame) :
    Prop :=
  t.1 ≠ t.2.1 ∧
    t.2.2 ∉ Fano.system.block t.1 t.2.1

/--
The frame predicate is decidable because the Fano point
set and its generated blocks are finite.
-/
instance isFrameDecidable
    (t : RawFrame) :
    Decidable (IsFrame t) := by
  unfold IsFrame
  infer_instance

/--
The type of ordered noncollinear Fano frames.
-/
abbrev Frame :=
  {t : RawFrame // IsFrame t}

/--
An ordered noncollinear Fano frame has three named points.
-/
def first
    (f : Frame) :
    Fano.Point :=
  f.1.1

def second
    (f : Frame) :
    Fano.Point :=
  f.1.2.1

def third
    (f : Frame) :
    Fano.Point :=
  f.1.2.2

/--
The first two points of a frame are distinct.
-/
theorem first_ne_second
    (f : Frame) :
    first f ≠ second f := by
  exact f.2.1

/--
The third point of a frame lies outside the Fano block
generated by its first two points.
-/
theorem third_not_mem_generated_block
    (f : Frame) :
    third f ∉
      Fano.system.block
        (first f)
        (second f) := by
  exact f.2.2

/--
There are exactly 168 ordered noncollinear frames of
the Fano plane.
-/
theorem card_frame :
    Fintype.card Frame = 168 := by
  native_decide

/-
The cardinality has been computationally verified as 168.

A permanent structural proof will count:
* seven choices for the first point,
* six choices for the distinct second point,
* four choices outside their generated Fano line.
-/

end FanoFrame
