import KTLean.Fano
import KTLean.YangBaxterRouting

/-!
# Fano Recovery and Structural Residue

This module audits what the preceding reconstruction
actually determines.

It establishes:

1. all blocks generated by distinct pairs recover exactly
   the seven lines of the Fano plane;

2. Fano completion and incidence are invariant under the
   coherent routed exchange;

3. two distinct routed states can have the same observable
   block and payload, and even the same Pascal control state,
   while retaining distinct Pascal addresses.

The third result is not treated as failure. It formally
identifies structured residual information that may later
serve tokenization and memory escrow.

This module does not claim that Pascal routing uniquely
forces the Fano completion table.
-/

namespace FanoRecovery


/-
## Recovery of the seven Fano lines
-/

/--
Ordered pairs of distinct Fano points.
-/
def distinctPairs :
    Finset (Fano.Point × Fano.Point) :=

  (Finset.univ :
      Finset (Fano.Point × Fano.Point)).filter
    (fun pair =>
      pair.1 ≠ pair.2)


/--
All Steiner blocks recovered from distinct point pairs.
-/
def recoveredLines :
    Finset (Finset Fano.Point) :=

  distinctPairs.image
    (fun pair =>
      Fano.system.block
        pair.1
        pair.2)


/--
Pairwise Steiner completion recovers exactly the seven
explicit Fano lines.
-/
theorem recoveredLines_eq_fanoLines :
    recoveredLines =
      Fano.lines := by

  decide


/--
The recovered incidence structure contains exactly
seven lines.
-/
theorem recoveredLines_card :
    recoveredLines.card = 7 := by

  calc
    recoveredLines.card =
        Fano.lines.card := by
          rw [recoveredLines_eq_fanoLines]

    _ = 7 := by
          exact Fano.lines_card


/--
Every block generated by two distinct points belongs to
the recovered Fano incidence structure.
-/
theorem generated_block_mem_recoveredLines
    {x y : Fano.Point}
    (hxy : x ≠ y) :

    Fano.system.block x y ∈
      recoveredLines := by

  apply Finset.mem_image.mpr

  refine
    ⟨(x, y), ?_, rfl⟩

  simp [
    distinctPairs,
    hxy
  ]


/--
Every block generated by two distinct points is one of
the seven Fano lines.
-/
theorem generated_block_mem_fanoLines
    {x y : Fano.Point}
    (hxy : x ≠ y) :

    Fano.system.block x y ∈
      Fano.lines := by

  have hmem :
      Fano.system.block x y ∈
        recoveredLines :=

    generated_block_mem_recoveredLines
      hxy

  rw [recoveredLines_eq_fanoLines] at hmem

  exact hmem


/-
## Recovery from routed packets
-/

/--
A routed packet whose payload is a Fano point.
-/
abbrev PointPacket :=
  YangBaxterRouting.RoutedPacket
    Fano.Point


/--
Recover the unique third Fano point from the payloads of
two routed packets.

The Pascal addresses do not enter this operation.
-/
def recoverThird
    (left right : PointPacket) :
    Fano.Point :=

  Fano.system.complete
    left.payload
    right.payload


/--
Recover the Fano block generated by two packet payloads.
-/
def recoverBlock
    (left right : PointPacket) :
    Finset Fano.Point :=

  Fano.system.block
    left.payload
    right.payload


/--
The recovered third point is the unique Steiner completion
of the two packet payloads.
-/
theorem recoverThird_unique
    (left right : PointPacket) :

    ∃! point : Fano.Point,
      Fano.system.Completes
        left.payload
        right.payload
        point := by

  exact
    Fano.system.existsUnique_completion
      left.payload
      right.payload


/--
Distinct packet payloads recover a three-point block.
-/
theorem recoverBlock_card
    {left right : PointPacket}
    (hdistinct :
      left.payload ≠ right.payload) :

    (recoverBlock left right).card =
      3 := by

  exact
    Fano.system.card_block_of_ne
      hdistinct


/--
Distinct packet payloads recover one of the seven Fano
lines.
-/
theorem recoverBlock_mem_fanoLines
    {left right : PointPacket}
    (hdistinct :
      left.payload ≠ right.payload) :

    recoverBlock left right ∈
      Fano.lines := by

  exact
    generated_block_mem_fanoLines
      hdistinct


/-
## Exchange coherence
-/

/--
Exchanging two routed packets does not change their
recovered third Fano point.
-/
theorem recoverThird_exchange
    (left right : PointPacket) :

    recoverThird
        (YangBaxterRouting.routedExchange
          (left, right)).1

        (YangBaxterRouting.routedExchange
          (left, right)).2 =

      recoverThird left right := by

  change
    Fano.system.complete
        right.payload
        left.payload =

      Fano.system.complete
        left.payload
        right.payload

  exact
    Fano.system.complete_comm
      right.payload
      left.payload


/--
Exchanging two routed packets preserves the recovered
Fano block.
-/
theorem recoverBlock_exchange
    (left right : PointPacket) :

    recoverBlock
        (YangBaxterRouting.routedExchange
          (left, right)).1

        (YangBaxterRouting.routedExchange
          (left, right)).2 =

      recoverBlock left right := by

  change
    Fano.system.block
        right.payload
        left.payload =

      Fano.system.block
        left.payload
        right.payload

  exact
    Fano.system.block_comm
      right.payload
      left.payload


/--
The Fano block recovered from the exterior packets of a
routed triple.
-/
def exteriorBlock
    (triple :
      YangBaxterRouting.Triple
        PointPacket) :

    Finset Fano.Point :=

  Fano.system.block
    triple.first.payload
    triple.third.payload


/--
The left Yang–Baxter braid path preserves the recovered
exterior Fano block.
-/
theorem leftBraid_preserves_exteriorBlock
    (triple :
      YangBaxterRouting.Triple
        PointPacket) :

    exteriorBlock
        (
          YangBaxterRouting.leftBraid
            (@YangBaxterRouting.routedExchange
              Fano.Point)
            triple
        ) =

      exteriorBlock triple := by

  rcases triple with
    ⟨left, middle, right⟩

  change
    Fano.system.block
        right.payload
        left.payload =

      Fano.system.block
        left.payload
        right.payload

  exact
    Fano.system.block_comm
      right.payload
      left.payload


/--
The right Yang–Baxter braid path preserves the recovered
exterior Fano block.
-/
theorem rightBraid_preserves_exteriorBlock
    (triple :
      YangBaxterRouting.Triple
        PointPacket) :

    exteriorBlock
        (
          YangBaxterRouting.rightBraid
            (@YangBaxterRouting.routedExchange
              Fano.Point)
            triple
        ) =

      exteriorBlock triple := by

  rcases triple with
    ⟨left, middle, right⟩

  change
    Fano.system.block
        right.payload
        left.payload =

      Fano.system.block
        left.payload
        right.payload

  exact
    Fano.system.block_comm
      right.payload
      left.payload


/--
Both Yang–Baxter paths recover the same exterior Fano
incidence block.
-/
theorem braid_paths_recover_same_exteriorBlock
    (triple :
      YangBaxterRouting.Triple
        PointPacket) :

    exteriorBlock
        (
          YangBaxterRouting.leftBraid
            (@YangBaxterRouting.routedExchange
              Fano.Point)
            triple
        ) =

      exteriorBlock
        (
          YangBaxterRouting.rightBraid
            (@YangBaxterRouting.routedExchange
              Fano.Point)
            triple
        ) := by

  calc
    exteriorBlock
        (
          YangBaxterRouting.leftBraid
            (@YangBaxterRouting.routedExchange
              Fano.Point)
            triple
        ) =

        exteriorBlock triple := by

          exact
            leftBraid_preserves_exteriorBlock
              triple

    _ =
        exteriorBlock
          (
            YangBaxterRouting.rightBraid
              (@YangBaxterRouting.routedExchange
                Fano.Point)
              triple
          ) := by

          symm

          exact
            rightBraid_preserves_exteriorBlock
              triple


/-
## Structured routing residue
-/

/--
Two distinct Pascal addresses carrying the same positive
control state.
-/
def routeA :
    BraidedQuaternion.PascalAddress :=
  ⟨0, 0⟩


def routeB :
    BraidedQuaternion.PascalAddress :=
  ⟨1, 0⟩


theorem routeA_ne_routeB :
    routeA ≠ routeB := by
  decide


@[simp]
theorem controlAt_routeA :
    BraidedQuaternion.controlAt routeA =
      PascalMod3.Control.positive := by
  decide


@[simp]
theorem controlAt_routeB :
    BraidedQuaternion.controlAt routeB =
      PascalMod3.Control.positive := by
  decide


/--
Lift a visible block and Fano point using the first
positive Pascal address.
-/
def liftA
    (block :
      CayleyDicksonQuaternion.Block)
    (point : Fano.Point) :
    PointPacket where

  block :=
    block

  address :=
    routeA

  payload :=
    point


/--
Lift the same visible data using a different positive
Pascal address.
-/
def liftB
    (block :
      CayleyDicksonQuaternion.Block)
    (point : Fano.Point) :
    PointPacket where

  block :=
    block

  address :=
    routeB

  payload :=
    point


@[simp]
theorem observable_liftA
    (block :
      CayleyDicksonQuaternion.Block)
    (point : Fano.Point) :

    YangBaxterRouting.RoutedPacket.observable
        (liftA block point) =

      (block, point) := by

  rfl


@[simp]
theorem observable_liftB
    (block :
      CayleyDicksonQuaternion.Block)
    (point : Fano.Point) :

    YangBaxterRouting.RoutedPacket.observable
        (liftB block point) =

      (block, point) := by

  rfl


@[simp]
theorem control_liftA
    (block :
      CayleyDicksonQuaternion.Block)
    (point : Fano.Point) :

    YangBaxterRouting.RoutedPacket.control
        (liftA block point) =

      PascalMod3.Control.positive := by

  change
    BraidedQuaternion.controlAt routeA =
      PascalMod3.Control.positive

  exact
    controlAt_routeA


@[simp]
theorem control_liftB
    (block :
      CayleyDicksonQuaternion.Block)
    (point : Fano.Point) :

    YangBaxterRouting.RoutedPacket.control
        (liftB block point) =

      PascalMod3.Control.positive := by

  change
    BraidedQuaternion.controlAt routeB =
      PascalMod3.Control.positive

  exact
    controlAt_routeB


/--
The two packet lifts remain distinct because their route
addresses remain distinct.
-/
theorem liftA_ne_liftB
    (block :
      CayleyDicksonQuaternion.Block)
    (point : Fano.Point) :

    liftA block point ≠
      liftB block point := by

  intro hequal

  have haddress :
      routeA = routeB := by

    simpa [
      liftA,
      liftB
    ] using

      congrArg
        (fun packet : PointPacket =>
          packet.address)
        hequal

  exact
    routeA_ne_routeB
      haddress


/--
Different hidden routes can have the same observable state
and the same Pascal control state.
-/
theorem structured_route_residue_exists :

    ∃ left right : PointPacket,

      left ≠ right ∧

      YangBaxterRouting.RoutedPacket.observable
          left =

        YangBaxterRouting.RoutedPacket.observable
          right ∧

      YangBaxterRouting.RoutedPacket.control
          left =

        YangBaxterRouting.RoutedPacket.control
          right := by

  refine
    ⟨
      liftA
        CayleyDicksonQuaternion.Block.first
        0,

      liftB
        CayleyDicksonQuaternion.Block.first
        0,

      ?_,
      ?_,
      ?_
    ⟩

  · exact
      liftA_ne_liftB
        CayleyDicksonQuaternion.Block.first
        0

  · rfl

  · simp


/--
Fano incidence recovery is insensitive to which of the two
residual positive routes carries a visible point.
-/
theorem recovery_ignores_route_residue
    (block :
      CayleyDicksonQuaternion.Block)
    (x y : Fano.Point) :

    recoverBlock
        (liftA block x)
        (liftA block y) =

      recoverBlock
        (liftB block x)
        (liftB block y) := by

  rfl


/-
## Constraint audit
-/

/--
A compact record of the current reconstruction boundary.
-/
structure ConstraintAudit where

  incidenceRecovered :
    recoveredLines =
      Fano.lines

  exchangePreservesIncidence :
    ∀ left right : PointPacket,

      recoverBlock
          (YangBaxterRouting.routedExchange
            (left, right)).1

          (YangBaxterRouting.routedExchange
            (left, right)).2 =

        recoverBlock left right

  braidPathsAgreeOnIncidence :
    ∀ triple :
        YangBaxterRouting.Triple
          PointPacket,

      exteriorBlock
          (
            YangBaxterRouting.leftBraid
              (@YangBaxterRouting.routedExchange
                Fano.Point)
              triple
          ) =

        exteriorBlock
          (
            YangBaxterRouting.rightBraid
              (@YangBaxterRouting.routedExchange
                Fano.Point)
              triple
          )

  structuredResidueExists :

    ∃ left right : PointPacket,

      left ≠ right ∧

      YangBaxterRouting.RoutedPacket.observable
          left =

        YangBaxterRouting.RoutedPacket.observable
          right ∧

      YangBaxterRouting.RoutedPacket.control
          left =

        YangBaxterRouting.RoutedPacket.control
          right


/--
The completed formal constraint audit.
-/
def audit :
    ConstraintAudit where

  incidenceRecovered :=
    recoveredLines_eq_fanoLines

  exchangePreservesIncidence :=
    recoverBlock_exchange

  braidPathsAgreeOnIncidence :=
    braid_paths_recover_same_exteriorBlock

  structuredResidueExists :=
    structured_route_residue_exists


end FanoRecovery


#check FanoRecovery.distinctPairs
#check FanoRecovery.recoveredLines
#check FanoRecovery.recoveredLines_eq_fanoLines
#check FanoRecovery.recoveredLines_card
#check FanoRecovery.generated_block_mem_fanoLines
#check FanoRecovery.PointPacket
#check FanoRecovery.recoverThird
#check FanoRecovery.recoverThird_unique
#check FanoRecovery.recoverBlock
#check FanoRecovery.recoverBlock_mem_fanoLines
#check FanoRecovery.recoverThird_exchange
#check FanoRecovery.recoverBlock_exchange
#check FanoRecovery.exteriorBlock
#check FanoRecovery.braid_paths_recover_same_exteriorBlock
#check FanoRecovery.routeA
#check FanoRecovery.routeB
#check FanoRecovery.routeA_ne_routeB
#check FanoRecovery.liftA
#check FanoRecovery.liftB
#check FanoRecovery.liftA_ne_liftB
#check FanoRecovery.structured_route_residue_exists
#check FanoRecovery.recovery_ignores_route_residue
#check FanoRecovery.ConstraintAudit
#check FanoRecovery.audit
