import KTLean.Steiner
import Mathlib.Data.Fin.VecNotation

/-!
# The Fano Steiner Triple System

This module constructs the Fano plane as an explicit
Steiner triple system on `Fin 7`.

The seven cyclic lines are

    {i, i+1, i+3} mod 7.

Equivalently:

    {0,1,3}
    {1,2,4}
    {2,3,5}
    {3,4,6}
    {4,5,0}
    {5,6,1}
    {6,0,2}

The completion table records the unique third point
on the line determined by each pair.

The Steiner identities are verified by finite computation.
-/

namespace Fano


/--
The seven points of the Fano plane.
-/
abbrev Point :=
  Fin 7


/--
The complete Fano Steiner operation table.

Diagonal entries fix the point. Every off-diagonal
entry is the unique third point on the Fano line
containing the two inputs.
-/
def completionTable :
    Point → Point → Point :=
  ![
    ![0, 3, 6, 1, 5, 4, 2],
    ![3, 1, 4, 0, 2, 6, 5],
    ![6, 4, 2, 5, 1, 3, 0],
    ![1, 0, 5, 3, 6, 2, 4],
    ![5, 2, 1, 6, 4, 0, 3],
    ![4, 6, 3, 2, 0, 5, 1],
    ![2, 5, 0, 4, 3, 1, 6]
  ]


/--
Fano completion of two points.
-/
def complete
    (x y : Point) :
    Point :=
  completionTable x y


/--
The diagonal of the Fano completion table fixes points.
-/
theorem complete_self :
    ∀ x : Point,
      complete x x = x := by
  decide


/--
Fano completion is commutative.
-/
theorem complete_comm :
    ∀ x y : Point,
      complete x y = complete y x := by
  decide


/--
Completing `x` with the third point determined by
`x` and `y` recovers `y`.
-/
theorem complete_left :
    ∀ x y : Point,
      complete x (complete x y) = y := by
  decide


/--
The Fano plane as an algebraic Steiner triple system.
-/
def system :
    Steiner.TripleSystem Point where

  complete :=
    complete

  complete_self :=
    complete_self

  complete_comm :=
    complete_comm

  complete_left :=
    complete_left


/--
The cyclic Fano line beginning at `i`.

Arithmetic in `Fin 7` is automatically reduced
modulo seven.
-/
def line
    (i : Point) :
    Finset Point :=
  {
    i,
    i + 1,
    i + 3
  }


/--
Every cyclic Fano line has exactly three points.
-/
theorem line_card :
    ∀ i : Point,
      (line i).card = 3 := by
  decide


/--
The cyclic line generated at `i` agrees with the
Steiner block generated by `i` and `i+1`.
-/
theorem line_eq_generated_block :
    ∀ i : Point,
      line i =
        system.block i (i + 1) := by
  decide


/--
The finite collection of all cyclic Fano lines.
-/
def lines :
    Finset (Finset Point) :=
  (Finset.univ : Finset Point).image line


/--
The cyclic construction produces exactly seven
distinct Fano lines.
-/
theorem lines_card :
    lines.card = 7 := by
  decide


/--
Every pair of points possesses one unique
Steiner completion.
-/
theorem pair_has_unique_completion
    (x y : Point) :
    ∃! z : Point,
      system.Completes x y z := by

  exact
    system.existsUnique_completion x y


/--
A pair of distinct Fano points generates a block
containing exactly three points.
-/
theorem distinct_pair_generates_three_points
    {x y : Point}
    (hxy : x ≠ y) :
    (system.block x y).card = 3 := by

  exact
    system.card_block_of_ne hxy


/--
The three points generated by a distinct pair are
pairwise distinct.
-/
theorem distinct_pair_has_distinct_completion
    {x y : Point}
    (hxy : x ≠ y) :
    x ≠ y ∧
    x ≠ system.complete x y ∧
    y ≠ system.complete x y := by

  exact
    system.completion_pairwise_distinct hxy


end Fano


#check Fano.Point
#check Fano.completionTable
#check Fano.complete
#check Fano.complete_self
#check Fano.complete_comm
#check Fano.complete_left
#check Fano.system
#check Fano.line
#check Fano.line_card
#check Fano.line_eq_generated_block
#check Fano.lines
#check Fano.lines_card
#check Fano.pair_has_unique_completion
#check Fano.distinct_pair_generates_three_points
#check Fano.distinct_pair_has_distinct_completion
