import KTLean.FluxDynamics
import KTLean.Reversibility

/-!
Reversible Flux dynamics in Kosmoplex Theory.

This module proves that the concrete fixed-context Flux
transition is an instance of the general reversible
dynamics developed in `KTLean.Reversibility`.
-/


/--
A fixed-context Flux transition represented as a
general reversible state transformation.

Because `fluxStep context` is involutive, the forward
transition and recovery transition are the same operation.
-/
def fluxReversibleStep
    (context : Flux) :
    ReversibleStep Flux :=
  ReversibleStep.ofInvolution
    (fluxStep context)
    (fluxStep_involutive context)


/--
The forward operation carried by the reversible structure
is the original fixed-context Flux transition.
-/
@[simp]
theorem fluxReversibleStep_step
    (context state : Flux) :
    (fluxReversibleStep context).step state =
      fluxStep context state := by
  rfl


/--
For fixed-context Flux dynamics, recovery uses the same
operation as forward evolution.
-/
@[simp]
theorem fluxReversibleStep_recover
    (context state : Flux) :
    (fluxReversibleStep context).recover state =
      fluxStep context state := by
  rfl


/--
The transition law of the reversible Flux structure is
the previously defined Flux transition law.
-/
theorem fluxReversibleLaw_eq_fluxLaw
    (context : Flux) :
    
    ReversibleStep.law (fluxReversibleStep context) =
      fluxLaw context := by
  rfl


/--
The history generated by the general reversible structure
is exactly the previously defined Flux history.
-/
theorem fluxReversibleHistory_eq_fluxHistory
    (context initial : Flux) :
    ReversibleStep.history
        (fluxReversibleStep context)
        initial =
      fluxHistory context initial := by
  rfl


/--
The preceding Flux state is recoverable from its successor
through the recovery operation carried by the reversible
structure.

This connects the concrete Flux result to the general
formal mechanism of one-step memory escrow.
-/
theorem fluxHistory_oneStep_recovery
    (context initial : Flux)
    (n : Nat) :
    (fluxReversibleStep context).recover
        (fluxHistory context initial (Nat.succ n)) =
      fluxHistory context initial n := by
  rw [← fluxReversibleHistory_eq_fluxHistory context initial]

  exact
    ReversibleStep.history_recovers_previous
      (fluxReversibleStep context)
      initial
      n


/--
The fixed-context Flux transition is injective as an
immediate consequence of its reversible structure.
-/
theorem fluxStep_injective_from_reversibility
    (context : Flux) :
    Function.Injective (fluxStep context) := by
  change Function.Injective
    (fluxReversibleStep context).step

  exact
    ReversibleStep.step_injective
      (fluxReversibleStep context)


/--
The fixed-context Flux transition is surjective as an
immediate consequence of its reversible structure.
-/
theorem fluxStep_surjective_from_reversibility
    (context : Flux) :
    Function.Surjective (fluxStep context) := by
  change Function.Surjective
    (fluxReversibleStep context).step

  exact
    ReversibleStep.step_surjective
      (fluxReversibleStep context)


#check fluxReversibleStep
#check fluxReversibleStep_step
#check fluxReversibleStep_recover
#check fluxReversibleLaw_eq_fluxLaw
#check fluxReversibleHistory_eq_fluxHistory
#check fluxHistory_oneStep_recovery
#check fluxStep_injective_from_reversibility
#check fluxStep_surjective_from_reversibility

