import KTLean.Flux
import KTLean.Axioms
import KTLean.Transition
import KTLean.Evolution

/-!
Concrete lawful evolution on the Flux substrate.

This module connects:

* Axiom 6 — triadic closure
* Axiom 7 — total and decidable transition
* Peano-indexed state history
-/


/--
Fixing one Flux state as a context turns the binary
triadic-completion operation into a unary transition.

The current state is transformed relative to `context`.
-/
def fluxStep (context : Flux) : Flux → Flux :=
  fun state => triadicCompletion state context


/--
The transition law generated by `fluxStep`.
-/
def fluxLaw (context : Flux) : TransitionLaw Flux :=
  graphLaw (fluxStep context)


/--
Every fixed-context Flux transition has a constructive
realization.
-/
def fluxRealization (context : Flux) :
    Realization (fluxLaw context) :=
  graphRealization (fluxStep context)


/--
Because equality on Flux is decidable, every fixed-context
Flux transition also has a decidable realization.
-/
def fluxDecidableRealization (context : Flux) :
    DecidableRealization (fluxLaw context) :=
  graphDecidableRealization (fluxStep context)


/--
When the state equals the context, triadic completion
leaves it unchanged.
-/
@[simp]
theorem fluxStep_diagonal
    (a : Flux) :
    fluxStep a a = a := by
  cases a <;> rfl


/--
When state and context are distinct, the transition
produces neither input and therefore produces the unique
third Flux state.
-/
theorem fluxStep_distinct
    (state context : Flux)
    (h : state ≠ context) :
    fluxStep context state ≠ state ∧
    fluxStep context state ≠ context := by
  simpa [fluxStep] using
    completion_satisfies_axiom6.2 state context h


/--
Every fixed-context Flux law is total and functional.
-/
theorem fluxLaw_totalFunctional
    (context : Flux) :
    TotalFunctional (fluxLaw context) := by
  simpa [fluxLaw] using
    graphLaw_totalFunctional (fluxStep context)


/--
The Peano-indexed history generated by a fixed-context
Flux transition.
-/
def fluxHistory
    (context initial : Flux) :
    Nat → Flux :=
  realizedHistory (fluxRealization context) initial


/--
Every adjacent pair in a Flux history satisfies the
corresponding Flux transition law.
-/
theorem fluxHistory_respects_law
    (context initial : Flux)
    (n : Nat) :
    fluxLaw context
      (fluxHistory context initial n)
      (fluxHistory context initial (Nat.succ n)) := by
  simpa [fluxHistory] using
    realizedHistory_respects_law
      (fluxRealization context) initial n


#check fluxStep
#check fluxLaw
#check fluxRealization
#check fluxDecidableRealization
#check fluxStep_diagonal
#check fluxStep_distinct
#check fluxLaw_totalFunctional
#check fluxHistory
#check fluxHistory_respects_law

/--
A fixed-context Flux transition is involutive.

Applying the same lawful transition twice restores
the original state.
-/
theorem fluxStep_involutive
    (context state : Flux) :
    fluxStep context (fluxStep context state) = state := by
  cases context <;> cases state <;> rfl


/--
Every fixed-context Flux transition is injective.

No two distinct prior states collapse into the same
successor state.
-/
theorem fluxStep_injective
    (context : Flux) :
    Function.Injective (fluxStep context) := by
  intro a b hab
  have h :=
    congrArg (fluxStep context) hab
  simpa [fluxStep_involutive] using h


/--
Every Flux state has a predecessor under a fixed-context
transition.
-/
theorem fluxStep_surjective
    (context : Flux) :
    Function.Surjective (fluxStep context) := by
  intro target
  exact ⟨fluxStep context target,
    fluxStep_involutive context target⟩


/--
Every fixed-context Flux transition is both injective
and surjective.
-/
theorem fluxStep_bijective
    (context : Flux) :
    Function.Injective (fluxStep context) ∧
    Function.Surjective (fluxStep context) := by
  exact ⟨fluxStep_injective context,
    fluxStep_surjective context⟩


/--
Successive entries of a Flux history are produced by
the fixed-context transition.
-/
@[simp]
theorem fluxHistory_succ
    (context initial : Flux)
    (n : Nat) :
    fluxHistory context initial (Nat.succ n) =
      fluxStep context (fluxHistory context initial n) := by
  rfl


/--
The preceding state can be recovered from the following
state by applying the same fixed-context transition.

This is the first concrete formal instance of memory
escrow in KTLean.
-/
theorem fluxHistory_recovers_previous
    (context initial : Flux)
    (n : Nat) :
    fluxStep context
      (fluxHistory context initial (Nat.succ n)) =
        fluxHistory context initial n := by
  rw [fluxHistory_succ]
  exact fluxStep_involutive
    context
    (fluxHistory context initial n)


#check fluxStep_involutive
#check fluxStep_injective
#check fluxStep_surjective
#check fluxStep_bijective
#check fluxHistory_succ
#check fluxHistory_recovers_previous
