import KTLean.Fano
import Mathlib.Data.Fintype.Card
import Mathlib.Tactic.FinCases

/-!
# The Frobenius orbit modulo seven

The multiplicative Frobenius orbit used in the canonical
KT glyph construction is

    1 → 2 → 4 → 1  modulo 7.

It is generated by repeated squaring:

    1² = 1,
    2² = 4,
    4² = 2  modulo 7.

Equivalently, beginning with `1` and applying the
doubling action on exponents gives:

    1 → 2 → 4 → 1.

This module isolates the three admissible Frobenius
steps as an exact finite type and proves their closure,
distinctness, and three-element cardinality.
-/

namespace FrobeniusOrbit

/--
The three canonical Frobenius steps used in the
42-glyph construction.
-/
inductive Step where
  | one
  | two
  | four
  deriving DecidableEq, Repr

/--
The numerical representative of a Frobenius step
inside the Fano arithmetic `Fin 7`.
-/
def Step.value : Step → Fano.Point
  | .one  => 1
  | .two  => 2
  | .four => 4

@[simp]
theorem Step.value_one :
    Step.one.value = 1 := by
  rfl

@[simp]
theorem Step.value_two :
    Step.two.value = 2 := by
  rfl

@[simp]
theorem Step.value_four :
    Step.four.value = 4 := by
  rfl

/--
Explicit finite enumeration of the Frobenius orbit.
-/
instance stepFintype : Fintype Step where
  elems := {Step.one, Step.two, Step.four}
  complete := by
    intro step
    cases step <;> simp

/--
There are exactly three Frobenius steps.
-/
theorem card_step :
    Fintype.card Step = 3 := by
  decide

/--
The canonical ordered Frobenius orbit.
-/
def steps : List Step :=
  [.one, .two, .four]

/--
The ordered numerical readout of the orbit.
-/
def values : List Fano.Point :=
  steps.map Step.value

theorem steps_length :
    steps.length = 3 := by
  native_decide

theorem values_length :
    values.length = 3 := by
  native_decide

theorem steps_nodup :
    steps.Nodup := by
  native_decide

theorem values_nodup :
    values.Nodup := by
  native_decide

/--
Every Frobenius step appears in the canonical list.
-/
theorem step_mem_steps
    (step : Step) :
    step ∈ steps := by
  cases step <;> decide

/--
The numerical representatives are exactly `1`, `2`,
and `4` in that order.
-/
theorem values_eq :
    values = [1, 2, 4] := by
  rfl

/--
Doubling an exponent modulo seven advances once
around the Frobenius orbit.
-/
def next : Step → Step
  | .one  => .two
  | .two  => .four
  | .four => .one

@[simp]
theorem next_one :
    next .one = .two := by
  rfl

@[simp]
theorem next_two :
    next .two = .four := by
  rfl

@[simp]
theorem next_four :
    next .four = .one := by
  rfl

/--
Advancing three times returns every Frobenius step
to itself.
-/
theorem next_three
    (step : Step) :
    next (next (next step)) = step := by
  cases step <;> rfl

/--
One advance never fixes a Frobenius step.
-/
theorem next_ne_self
    (step : Step) :
    next step ≠ step := by
  cases step <;> decide

/--
Two advances also never fix a Frobenius step.
-/
theorem next_next_ne_self
    (step : Step) :
    next (next step) ≠ step := by
  cases step <;> decide

/--
`next` acts numerically as multiplication by two
modulo seven.
-/
theorem value_next
    (step : Step) :
    (next step).value = step.value * 2 := by
  cases step <;> native_decide

/--
The three Frobenius representatives are nonzero
modulo seven.
-/
theorem value_ne_zero
    (step : Step) :
    step.value ≠ 0 := by
  cases step <;> decide

/--
Each representative satisfies `r³ = 1` modulo seven.
Thus the orbit lies inside the order-three subgroup
of the nonzero residues modulo seven.
-/
theorem value_cube_eq_one
    (step : Step) :
    step.value ^ 3 = 1 := by
  cases step <;> native_decide

/--
Squaring preserves the set `{1,2,4}`.
-/
def square : Step → Step
  | .one  => .one
  | .two  => .four
  | .four => .two

/--
The symbolic square operation agrees with numerical
squaring modulo seven.
-/
theorem value_square
    (step : Step) :
    (square step).value = step.value ^ 2 := by
  cases step <;> native_decide

/--
Squaring twice returns each Frobenius step to itself.
-/
theorem square_involution
    (step : Step) :
    square (square step) = step := by
  cases step <;> rfl

/--
The canonical three-cycle generated by exponent
doubling is exactly the numerical orbit `1,2,4`.
-/
theorem canonical_cycle :
    [
      Step.one.value,
      (next Step.one).value,
      (next (next Step.one)).value
    ] = [1, 2, 4] := by
  rfl

/--
Readable output for inspection.
-/
structure Entry where
  orbitPosition : Nat
  symbolicStep : Step
  numericalValue : Nat
  nextValue : Nat
  deriving Repr

def entryOfIndexedStep
    (entry : Step × Nat) :
    Entry :=
  {
    orbitPosition := entry.2 + 1
    symbolicStep := entry.1
    numericalValue := entry.1.value.val
    nextValue := (next entry.1).value.val
  }

def table : List Entry :=
  steps.zipIdx.map entryOfIndexedStep

theorem table_length :
    table.length = 3 := by
  native_decide

#eval table

end FrobeniusOrbit
