import KTLean.GlyphSpectralWallisLimit
import Mathlib.Tactic

/-!
# The Triadic Exponential Kernel

## Formal status

**Level 2 — Exact finite recurrence underlying the e glyph.**

At every stage the exponential process carries:

* an accumulated state `Sₙ`;
* a current increment `Tₙ`;
* a uniquely forced next increment `Tₙ₊₁ = Tₙ / (n + 1)`.

Additive closure then forces:

    Sₙ₊₁ = Sₙ + Tₙ₊₁.

Starting from `S₀ = 1` and `T₀ = 1`, this produces the partial sums of

    1 + 1 + 1/2! + 1/3! + ...

No analytic limit is asserted in this module. The next module will
identify the limit with `Real.exp 1`.
-/

namespace GlyphSpectralExponentialKernel

open GlyphSpectralTriadicEngine

/--
The indexed scaling law that forces the next exponential increment.
-/
def nextIncrement
    (n : Nat)
    (current : ℚ) :
    ℚ :=

  current / (n + 1)

/--
The next increment is uniquely determined.
-/
theorem existsUnique_nextIncrement
    (n : Nat)
    (current : ℚ) :
    ∃! next : ℚ,
      next =
        nextIncrement n current := by

  exact
    ⟨
      nextIncrement n current,
      rfl,
      by
        intro next h
        exact h
    ⟩

/--
One exponential recurrence state consists of the accumulated value and
the current increment.
-/
structure ExpState where

  accumulated : ℚ
  increment : ℚ

  deriving Repr, DecidableEq

/--
The initial exponential state.
-/
def initialState :
    ExpState where

  accumulated :=
    1

  increment :=
    1

/--
Advance one exponential stage.

The old increment and the stage index force the new increment. The old
accumulation and new increment then force the new accumulation.
-/
def advance
    (n : Nat)
    (state : ExpState) :
    ExpState :=

  let next :=
    nextIncrement n state.increment

  {
    accumulated :=
      state.accumulated + next

    increment :=
      next
  }

/--
The deterministic exponential orbit.
-/
def orbit :
    Nat →
      ExpState

  | 0 =>
      initialState

  | n + 1 =>
      advance
        n
        (orbit n)

/--
The initial state is `(1,1)`.
-/
@[simp]
theorem orbit_zero :
    orbit 0 =
      initialState := by

  rfl

/--
The successor orbit is generated by one deterministic closure step.
-/
@[simp]
theorem orbit_succ
    (n : Nat) :
    orbit (n + 1) =
      advance
        n
        (orbit n) := by

  rfl

/--
The next increment is the previous increment divided by `n+1`.
-/
theorem orbit_increment_succ
    (n : Nat) :
    (orbit (n + 1)).increment =
      (orbit n).increment / (n + 1) := by

  rfl

/--
The next accumulated value is the old value plus the newly forced
increment.
-/
theorem orbit_accumulated_succ
    (n : Nat) :
    (orbit (n + 1)).accumulated =
      (orbit n).accumulated
        +
      (orbit (n + 1)).increment := by

  rfl

/--
Every increment remains positive.
-/
theorem orbit_increment_positive
    (n : Nat) :
    0 <
      (orbit n).increment := by

  induction n with

  | zero =>
      norm_num [
        orbit,
        initialState
      ]

  | succ n ih =>
      rw [
        orbit_increment_succ
      ]

      exact
        div_pos
          ih
          (
            by
              positivity
          )

/--
Every accumulated value remains positive.
-/
theorem orbit_accumulated_positive
    (n : Nat) :
    0 <
      (orbit n).accumulated := by

  induction n with

  | zero =>
      norm_num [
        orbit,
        initialState
      ]

  | succ n ih =>
      rw [
        orbit_accumulated_succ
      ]

      exact
        add_pos
          ih
          (
            orbit_increment_positive
              (n + 1)
          )

/--
The accumulated sequence increases strictly at every stage.
-/
theorem orbit_accumulated_strictly_increases
    (n : Nat) :
    (orbit n).accumulated
      <
    (orbit (n + 1)).accumulated := by

  rw [
    orbit_accumulated_succ
  ]

  exact
    lt_add_of_pos_right
      _
      (
        orbit_increment_positive
          (n + 1)
      )

/--
The first recurrence step gives increment `1` and accumulation `2`.
-/
theorem orbit_one :
    orbit 1 =
      {
        accumulated := 2
        increment := 1
      } := by

  norm_num [
    orbit,
    advance,
    initialState,
    nextIncrement
  ]

/--
The second recurrence step gives increment `1/2` and accumulation
`5/2`.
-/
theorem orbit_two :
    orbit 2 =
      {
        accumulated := 5 / 2
        increment := 1 / 2
      } := by

  norm_num [
    orbit,
    advance,
    initialState,
    nextIncrement
  ]

/--
The third recurrence step gives increment `1/6` and accumulation
`8/3`.
-/
theorem orbit_three :
    orbit 3 =
      {
        accumulated := 8 / 3
        increment := 1 / 6
      } := by

  norm_num [
    orbit,
    advance,
    initialState,
    nextIncrement
  ]

/--
The symbolic spectrum registers the reciprocal exponential pair at
glyphs 9 and 10.
-/
theorem registered_exponential_pair :
    GlyphSpectrum.values[8]? =
        some
          (.inverse .eulerNumber)
      ∧
    GlyphSpectrum.values[9]? =
        some
          .eulerNumber := by

  native_decide

/--
At every depth, the current state and stage index determine exactly one
next state.
-/
theorem existsUnique_successorState
    (n : Nat)
    (state : ExpState) :
    ∃! next : ExpState,
      next =
        advance n state := by

  exact
    ⟨
      advance n state,
      rfl,
      by
        intro next h
        exact h
    ⟩

/--
Capstone theorem.

The unit exponential stream is generated by deterministic triadic
closure: one current increment and one stage divisor force a unique new
increment, while the current accumulation and that increment force a
unique new accumulation.
-/
theorem triadic_recurrence_forces_exponential_stream :
    (∀ n : Nat,
      (orbit (n + 1)).increment =
        (orbit n).increment / (n + 1))
      ∧
    (∀ n : Nat,
      (orbit (n + 1)).accumulated =
        (orbit n).accumulated
          +
        (orbit (n + 1)).increment)
      ∧
    (∀ n : Nat,
      0 <
        (orbit n).increment)
      ∧
    (∀ n : Nat,
      (orbit n).accumulated
        <
      (orbit (n + 1)).accumulated)
      ∧
    GlyphSpectrum.values[8]? =
        some
          (.inverse .eulerNumber)
      ∧
    GlyphSpectrum.values[9]? =
        some
          .eulerNumber := by

  exact
    ⟨
      orbit_increment_succ,
      orbit_accumulated_succ,
      orbit_increment_positive,
      orbit_accumulated_strictly_increases,
      registered_exponential_pair.1,
      registered_exponential_pair.2
    ⟩

end GlyphSpectralExponentialKernel

#check GlyphSpectralExponentialKernel.nextIncrement
#check GlyphSpectralExponentialKernel.existsUnique_nextIncrement
#check GlyphSpectralExponentialKernel.ExpState
#check GlyphSpectralExponentialKernel.initialState
#check GlyphSpectralExponentialKernel.advance
#check GlyphSpectralExponentialKernel.orbit
#check GlyphSpectralExponentialKernel.orbit_increment_succ
#check GlyphSpectralExponentialKernel.orbit_accumulated_succ
#check GlyphSpectralExponentialKernel.orbit_increment_positive
#check GlyphSpectralExponentialKernel.orbit_accumulated_positive
#check GlyphSpectralExponentialKernel.orbit_accumulated_strictly_increases
#check GlyphSpectralExponentialKernel.orbit_one
#check GlyphSpectralExponentialKernel.orbit_two
#check GlyphSpectralExponentialKernel.orbit_three
#check GlyphSpectralExponentialKernel.registered_exponential_pair
#check GlyphSpectralExponentialKernel.existsUnique_successorState
#check GlyphSpectralExponentialKernel.triadic_recurrence_forces_exponential_stream
