import KTLean.GlyphSpectralFrobeniusBoundary
import Mathlib.Tactic

/-!
# Fundamental Integer Spectrum from Triadic Closure

## Formal status

**Level 2 — Exact finite derivation of the first six spectral values.**

The first six entries of the canonical glyph spectrum are

    1, 2, 3, 4, 7, 8.

They arise from the basic KT hierarchy:

* one grounding state;
* two forcing inputs;
* one uniquely completed triad;
* grounding plus the triad;
* the forced seven-point Fano carrier;
* grounding plus the Fano carrier.

Thus:

    1
    2
    3 = 2 + 1
    4 = 1 + 3
    7
    8 = 1 + 7.

No analytic constants or projection assumptions occur in this module.
-/

namespace GlyphSpectralFundamentalIntegers

/--
The unique grounding state.
-/
def groundingCount :
    Nat :=
  1

/--
The number of forcing inputs in one closure event.
-/
def forcingInputCount :
    Nat :=
  2

/--
Two inputs together with their unique completion form one triad.
-/
def closedTriadCount :
    Nat :=
  forcingInputCount + groundingCount

/--
Grounding together with one closed triad gives the local four-state
closure frame.
-/
def localClosureFrameCount :
    Nat :=
  groundingCount + closedTriadCount

/--
The forced Fano carrier contains seven points.
-/
def fanoCarrierCount :
    Nat :=
  7

/--
Grounding together with the seven-point carrier gives eight states.
-/
def groundedFanoCarrierCount :
    Nat :=
  groundingCount + fanoCarrierCount

/--
There is exactly one grounding state.
-/
theorem groundingCount_eq_one :
    groundingCount =
      1 := by

  rfl

/--
A closure event begins from exactly two forcing inputs.
-/
theorem forcingInputCount_eq_two :
    forcingInputCount =
      2 := by

  rfl

/--
Two forcing inputs and one unique completion form three states.
-/
theorem closedTriadCount_eq_three :
    closedTriadCount =
      3 := by

  rfl

/--
Grounding plus a closed triad gives four states.
-/
theorem localClosureFrameCount_eq_four :
    localClosureFrameCount =
      4 := by

  rfl

/--
The forced Fano carrier contains seven points.
-/
theorem fanoCarrierCount_eq_seven :
    fanoCarrierCount =
      7 := by

  rfl

/--
Grounding plus the Fano carrier gives eight states.
-/
theorem groundedFanoCarrierCount_eq_eight :
    groundedFanoCarrierCount =
      8 := by

  rfl

/--
The local hierarchy is generated by successive closure additions.
-/
theorem local_closure_chain :
    closedTriadCount =
        forcingInputCount + groundingCount
      ∧
    localClosureFrameCount =
        groundingCount + closedTriadCount := by

  exact
    ⟨
      rfl,
      rfl
    ⟩

/--
The global eight-state count is grounding plus the forced seven-point
carrier.
-/
theorem grounded_fano_chain :
    groundedFanoCarrierCount =
      groundingCount + fanoCarrierCount := by

  rfl

/--
The first six registered spectral entries.
-/
def registeredFundamentalBlock :
    List GlyphSpectrum.SpectralValue :=

  GlyphSpectrum.values.take 6

/--
The registered fundamental block is exactly

    1, 2, 3, 4, 7, 8.
-/
theorem registeredFundamentalBlock_eq :
    registeredFundamentalBlock =
      [
        .natural 1,
        .natural 2,
        .natural 3,
        .natural 4,
        .natural 7,
        .natural 8
      ] := by

  native_decide

/--
Each structural count occurs at its canonical spectrum position.
-/
theorem fundamental_registered_positions :
    GlyphSpectrum.values[0]? =
        some (.natural 1)
      ∧
    GlyphSpectrum.values[1]? =
        some (.natural 2)
      ∧
    GlyphSpectrum.values[2]? =
        some (.natural 3)
      ∧
    GlyphSpectrum.values[3]? =
        some (.natural 4)
      ∧
    GlyphSpectrum.values[4]? =
        some (.natural 7)
      ∧
    GlyphSpectrum.values[5]? =
        some (.natural 8) := by

  native_decide

/--
The triadic motif appears explicitly in the first four values:

    3 = 2 + 1
    4 = 1 + 3.
-/
theorem triadic_generation_of_three_and_four :
    closedTriadCount =
        forcingInputCount + groundingCount
      ∧
    localClosureFrameCount =
        groundingCount + closedTriadCount
      ∧
    closedTriadCount =
        3
      ∧
    localClosureFrameCount =
        4 := by

  exact
    ⟨
      rfl,
      rfl,
      closedTriadCount_eq_three,
      localClosureFrameCount_eq_four
    ⟩

/--
Capstone theorem.

The first six canonical spectral values are the exact counts generated
by grounding, binary forcing, unique triadic completion, the local
four-state closure frame, the forced seven-point Fano carrier, and its
grounded eight-state completion.
-/
theorem triadic_hierarchy_forces_fundamental_block :
    groundingCount =
        1
      ∧
    forcingInputCount =
        2
      ∧
    closedTriadCount =
        3
      ∧
    localClosureFrameCount =
        4
      ∧
    fanoCarrierCount =
        7
      ∧
    groundedFanoCarrierCount =
        8
      ∧
    registeredFundamentalBlock =
      [
        .natural 1,
        .natural 2,
        .natural 3,
        .natural 4,
        .natural 7,
        .natural 8
      ] := by

  exact
    ⟨
      groundingCount_eq_one,
      forcingInputCount_eq_two,
      closedTriadCount_eq_three,
      localClosureFrameCount_eq_four,
      fanoCarrierCount_eq_seven,
      groundedFanoCarrierCount_eq_eight,
      registeredFundamentalBlock_eq
    ⟩

end GlyphSpectralFundamentalIntegers

#check GlyphSpectralFundamentalIntegers.groundingCount
#check GlyphSpectralFundamentalIntegers.forcingInputCount
#check GlyphSpectralFundamentalIntegers.closedTriadCount
#check GlyphSpectralFundamentalIntegers.localClosureFrameCount
#check GlyphSpectralFundamentalIntegers.fanoCarrierCount
#check GlyphSpectralFundamentalIntegers.groundedFanoCarrierCount
#check GlyphSpectralFundamentalIntegers.closedTriadCount_eq_three
#check GlyphSpectralFundamentalIntegers.localClosureFrameCount_eq_four
#check GlyphSpectralFundamentalIntegers.groundedFanoCarrierCount_eq_eight
#check GlyphSpectralFundamentalIntegers.registeredFundamentalBlock_eq
#check GlyphSpectralFundamentalIntegers.fundamental_registered_positions
#check GlyphSpectralFundamentalIntegers.triadic_hierarchy_forces_fundamental_block
