import KTLean.GlyphAttractorTableBridge
import KTLean.GlyphForcingFrobeniusIdentification

/-!
# The Triadic Engine Underlying Glyph Spectral Recurrence

## Formal status

**Level 2 — Abstract deterministic recurrence architecture.**

The canonical KT spectral construction is governed by one recurring
motif:

    two existing states force one unique third state.

This module isolates that motif before any named constants are
introduced.

A closure law is a total function

    α → α → α.

For every ordered pair `(x,y)`, the law therefore determines exactly
one completion `z`.

The forced glyph coordinates then select:

* one of three recurrence modes through the forced Frobenius role;
* one of two framed branches through orientation;
* one seed pair through the forced Fano address.

No spectral value is registered or looked up in this module.

Later modules must instantiate this engine with concrete additive,
multiplicative, geometric, harmonic, or boundary closure laws and prove
their fixed points, limits, or finite invariants.
-/

namespace GlyphSpectralTriadicEngine

universe u

open GlyphForcingTriadicRole
open GlyphForcingOrientation
open GlyphForcingPrimitiveWalk
open GlyphForcingFrobeniusIdentification

/--
A total two-parent closure law.

Two inputs determine one output.
-/
abbrev ClosureLaw
    (α : Type u) :=
  α → α → α

/--
`z` completes `x` and `y` under one closure law.
-/
def Completes
    {α : Type u}
    (law : ClosureLaw α)
    (x y z : α) :
    Prop :=

  z =
    law x y

/--
Every ordered input pair has exactly one completion.
-/
theorem existsUnique_completion
    {α : Type u}
    (law : ClosureLaw α)
    (x y : α) :
    ∃! z : α,
      Completes law x y z := by

  refine
    ⟨
      law x y,
      rfl,
      ?_
    ⟩

  intro z hCompletion

  exact
    hCompletion

/--
The three recurrence modes selected by the forced Frobenius role.

No analytic interpretation is imposed here.
-/
abbrev RecurrenceMode :=
  ForcedRole

/--
Readable names for the three forced recurrence modes.
-/
def additiveMode :
    RecurrenceMode :=
  0

def multiplicativeMode :
    RecurrenceMode :=
  1

def geometricMode :
    RecurrenceMode :=
  2

/--
The three recurrence modes exhaust the forced role carrier.
-/
theorem recurrenceMode_exhausted
    (mode : RecurrenceMode) :
    mode = additiveMode
      ∨
    mode = multiplicativeMode
      ∨
    mode = geometricMode := by

  fin_cases mode

  · exact Or.inl rfl

  · exact Or.inr (Or.inl rfl)

  · exact Or.inr (Or.inr rfl)

/--
The recurrence-mode cycle is the already forced Frobenius cycle.
-/
theorem recurrenceMode_cycle_is_frobenius
    (mode : RecurrenceMode) :
    stepOfForcedRole
        (nextRole mode) =
      FrobeniusOrbit.next
        (stepOfForcedRole mode) := by

  exact
    stepOfForcedRole_nextRole
      mode

/--
A framed family supplies one total closure law for each forced
recurrence mode and each forced orientation.
-/
structure FramedClosureFamily
    (α : Type u) where

  law :
    RecurrenceMode →
      ForcedOrientation →
        ClosureLaw α

/--
A seed family supplies one ordered input pair at every forced Fano
address.
-/
abbrev SeedFamily
    (α : Type u) :=
  Fano.Point →
    α × α

/--
Select the closure law determined by one forced primitive walk.
-/
def lawOfWalk
    {α : Type u}
    (family : FramedClosureFamily α)
    (walk : PrimitiveWalk) :
    ClosureLaw α :=

  family.law
    walk.2.1
    walk.2.2

/--
Select the seed pair determined by the Fano address of one forced
primitive walk.
-/
def seedOfWalk
    {α : Type u}
    (seeds : SeedFamily α)
    (walk : PrimitiveWalk) :
    α × α :=

  seeds walk.1

/--
The unique first completion generated by one forced glyph address.
-/
def firstCompletion
    {α : Type u}
    (family : FramedClosureFamily α)
    (seeds : SeedFamily α)
    (walk : PrimitiveWalk) :
    α :=

  lawOfWalk family walk
    (seedOfWalk seeds walk).1
    (seedOfWalk seeds walk).2

/--
Every forced primitive walk determines one unique first completion.
-/
theorem walk_has_unique_firstCompletion
    {α : Type u}
    (family : FramedClosureFamily α)
    (seeds : SeedFamily α)
    (walk : PrimitiveWalk) :
    ∃! z : α,
      Completes
        (lawOfWalk family walk)
        (seedOfWalk seeds walk).1
        (seedOfWalk seeds walk).2
        z := by

  exact
    existsUnique_completion
      (lawOfWalk family walk)
      (seedOfWalk seeds walk).1
      (seedOfWalk seeds walk).2

/--
Advance an ordered recurrence state by retaining the second input and
adjoining the uniquely forced completion.
-/
def advance
    {α : Type u}
    (law : ClosureLaw α)
    (state : α × α) :
    α × α :=

  (
    state.2,
    law state.1 state.2
  )

/--
One seeded recurrence engine.
-/
structure SeededEngine
    (α : Type u) where

  law :
    ClosureLaw α

  seed :
    α × α

/--
Construct the recurrence engine selected by one forced primitive walk.
-/
def engineOfWalk
    {α : Type u}
    (family : FramedClosureFamily α)
    (seeds : SeedFamily α)
    (walk : PrimitiveWalk) :
    SeededEngine α where

  law :=
    lawOfWalk family walk

  seed :=
    seedOfWalk seeds walk

/--
The deterministic state orbit generated by one seeded engine.
-/
def orbit
    {α : Type u}
    (engine : SeededEngine α) :
    Nat →
      α × α

  | 0 =>
      engine.seed

  | n + 1 =>
      advance
        engine.law
        (orbit engine n)

/--
The initial orbit state is the supplied seed.
-/
@[simp]
theorem orbit_zero
    {α : Type u}
    (engine : SeededEngine α) :
    orbit engine 0 =
      engine.seed := by

  rfl

/--
Every successor orbit state is obtained by one triadic completion
step.
-/
@[simp]
theorem orbit_succ
    {α : Type u}
    (engine : SeededEngine α)
    (n : Nat) :
    orbit engine (n + 1) =
      advance
        engine.law
        (orbit engine n) := by

  rfl

/--
The second component of every successor state is the unique completion
of the preceding ordered pair.
-/
theorem orbit_successor_completion
    {α : Type u}
    (engine : SeededEngine α)
    (n : Nat) :
    Completes
        engine.law
        (orbit engine n).1
        (orbit engine n).2
        (orbit engine (n + 1)).2 := by

  rfl

/--
At every recurrence depth, there is exactly one legal next value.
-/
theorem orbit_has_unique_nextValue
    {α : Type u}
    (engine : SeededEngine α)
    (n : Nat) :
    ∃! z : α,
      Completes
        engine.law
        (orbit engine n).1
        (orbit engine n).2
        z := by

  exact
    existsUnique_completion
      engine.law
      (orbit engine n).1
      (orbit engine n).2

/--
A map between carriers intertwines two closure laws when it preserves
every forced completion.
-/
def Intertwines
    {α : Type u}
    {β : Type u}
    (map : α → β)
    (lawα : ClosureLaw α)
    (lawβ : ClosureLaw β) :
    Prop :=

  ∀ x y,
    map (lawα x y) =
      lawβ (map x) (map y)

/--
Intertwining maps preserve one recurrence advance.
-/
theorem map_advance
    {α : Type u}
    {β : Type u}
    (map : α → β)
    (lawα : ClosureLaw α)
    (lawβ : ClosureLaw β)
    (hIntertwines :
      Intertwines map lawα lawβ)
    (state : α × α) :
    (
      map (advance lawα state).1,
      map (advance lawα state).2
    ) =
      advance
        lawβ
        (
          map state.1,
          map state.2
        ) := by

  apply Prod.ext

  · rfl

  · exact
      hIntertwines
        state.1
        state.2

/--
Capstone statement.

Every forced glyph address selects a total framed closure law and a
seed pair. At every depth, two current states force one and only one
next state.
-/
theorem forced_glyph_recurrence_is_triadically_deterministic
    {α : Type u}
    (family : FramedClosureFamily α)
    (seeds : SeedFamily α)
    (walk : PrimitiveWalk) :
    (∃! z : α,
      Completes
        (lawOfWalk family walk)
        (seedOfWalk seeds walk).1
        (seedOfWalk seeds walk).2
        z)
      ∧
    (∀ n,
      ∃! z : α,
        Completes
          (engineOfWalk family seeds walk).law
          (orbit
            (engineOfWalk family seeds walk)
            n).1
          (orbit
            (engineOfWalk family seeds walk)
            n).2
          z) := by

  exact
    ⟨
      walk_has_unique_firstCompletion
        family
        seeds
        walk,
      by
        intro n

        exact
          orbit_has_unique_nextValue
            (engineOfWalk family seeds walk)
            n
    ⟩

end GlyphSpectralTriadicEngine

#check GlyphSpectralTriadicEngine.ClosureLaw
#check GlyphSpectralTriadicEngine.Completes
#check GlyphSpectralTriadicEngine.existsUnique_completion
#check GlyphSpectralTriadicEngine.RecurrenceMode
#check GlyphSpectralTriadicEngine.recurrenceMode_exhausted
#check GlyphSpectralTriadicEngine.recurrenceMode_cycle_is_frobenius
#check GlyphSpectralTriadicEngine.FramedClosureFamily
#check GlyphSpectralTriadicEngine.SeedFamily
#check GlyphSpectralTriadicEngine.lawOfWalk
#check GlyphSpectralTriadicEngine.seedOfWalk
#check GlyphSpectralTriadicEngine.firstCompletion
#check GlyphSpectralTriadicEngine.walk_has_unique_firstCompletion
#check GlyphSpectralTriadicEngine.advance
#check GlyphSpectralTriadicEngine.SeededEngine
#check GlyphSpectralTriadicEngine.engineOfWalk
#check GlyphSpectralTriadicEngine.orbit
#check GlyphSpectralTriadicEngine.orbit_successor_completion
#check GlyphSpectralTriadicEngine.orbit_has_unique_nextValue
#check GlyphSpectralTriadicEngine.Intertwines
#check GlyphSpectralTriadicEngine.map_advance
#check GlyphSpectralTriadicEngine.forced_glyph_recurrence_is_triadically_deterministic
