import KTLean.OMBTProjectionInterface
import KTLean.TkairosLocality
import Mathlib.Tactic

/-!
# OMBT Generation of Locality

## Formal status

**Level 2 — Locality as the visible quotient of a complete
projection-with-escrow state.**

## Developmental predecessor

`OMBTProjectionInterface`

The complete pre-projection state does not begin inside an independently
assumed locality. The OMBT produces two coordinated readouts:

    complete state
          ↓
    visible local state + escrow state.

The visible projection identifies complete states that differ only in
hidden routing information. Consequently, a visible locality is not the
complete source state. It is an observational quotient whose fibers
contain structured hidden residue.

Escrow distinguishes the complete states within each visible fiber.
Therefore:

* the visible projection alone is generally non-injective;
* visible state plus escrow remains fully injective;
* complete evolution factors through a lawful visible evolution;
* observationally equivalent complete states remain observationally
  equivalent after evolution.

This is the first formal sense in which locality emerges at projection
rather than existing beforehand.
-/

namespace OMBTLocalityGeneration

/-
## The visible projection generated by OMBT
-/

/--
The visible component of the routed OMBT regarded as a locality
projection.
-/
def ombtVisibleProjection :
    TkairosLocality.Projection
      MemoryEscrowRouted.CompleteState
      MemoryEscrowRouted.VisibleState where

  observe :=
    OMBTProjectionInterface.routedOMBT.visible

/--
The OMBT visible projection agrees definitionally with the established
routed observation.
-/
theorem ombtVisibleProjection_observe
    (source :
      MemoryEscrowRouted.CompleteState) :
    ombtVisibleProjection.observe source =
      TkairosLocality.observeRoutedPair source := by

  rfl

/--
Two complete states are locally indistinguishable when the OMBT gives
them the same visible projection.
-/
def LocallyEquivalent
    (left right :
      MemoryEscrowRouted.CompleteState) :
    Prop :=

  ombtVisibleProjection.Equivalent
    left
    right

/--
Local equivalence is equality of visible OMBT readouts.
-/
theorem locallyEquivalent_iff_visible_eq
    (left right :
      MemoryEscrowRouted.CompleteState) :
    LocallyEquivalent left right
      ↔
    OMBTProjectionInterface.routedOMBT.visible left =
      OMBTProjectionInterface.routedOMBT.visible right := by

  rfl

/--
Local equivalence is reflexive.
-/
theorem locallyEquivalent_refl
    (source :
      MemoryEscrowRouted.CompleteState) :
    LocallyEquivalent source source := by

  exact
    TkairosLocality.Projection.equivalent_refl
      ombtVisibleProjection
      source

/--
Local equivalence is symmetric.
-/
theorem locallyEquivalent_symm
    {left right :
      MemoryEscrowRouted.CompleteState}
    (hEquivalent :
      LocallyEquivalent left right) :
    LocallyEquivalent right left := by

  exact
    TkairosLocality.Projection.equivalent_symm
      ombtVisibleProjection
      hEquivalent

/--
Local equivalence is transitive.
-/
theorem locallyEquivalent_trans
    {left middle right :
      MemoryEscrowRouted.CompleteState}
    (hLeftMiddle :
      LocallyEquivalent left middle)
    (hMiddleRight :
      LocallyEquivalent middle right) :
    LocallyEquivalent left right := by

  exact
    TkairosLocality.Projection.equivalent_trans
      ombtVisibleProjection
      hLeftMiddle
      hMiddleRight

/-
## Local observable fibers
-/

/--
The complete-state fiber corresponding to one visible local state.
-/
def LocalFiber
    (visible :
      MemoryEscrowRouted.VisibleState) :
    Set MemoryEscrowRouted.CompleteState :=

  ombtVisibleProjection.Fiber visible

/--
A complete state belongs to a local fiber exactly when it produces the
corresponding visible state.
-/
theorem mem_localFiber
    (visible :
      MemoryEscrowRouted.VisibleState)
    (source :
      MemoryEscrowRouted.CompleteState) :
    source ∈ LocalFiber visible
      ↔
    OMBTProjectionInterface.routedOMBT.visible source =
      visible := by

  rfl

/--
The routed OMBT visible projection has structured hidden residue.

Distinct complete states can occupy the same visible local fiber.
-/
theorem ombt_visible_projection_has_residue :
    ombtVisibleProjection.HasResidue := by

  exact
    TkairosLocality.routed_hasHiddenResidue

/--
The visible projection alone is not injective.
-/
theorem ombt_visible_projection_not_injective :
    ¬ Function.Injective
        ombtVisibleProjection.observe := by

  exact
    TkairosLocality.routed_observe_not_injective

/--
There exists a visible local state whose fiber contains at least two
distinct complete states.
-/
theorem nontrivial_local_fiber_exists :
    ∃
      visible :
        MemoryEscrowRouted.VisibleState,
      ∃
        left right :
          MemoryEscrowRouted.CompleteState,
        left ≠ right
          ∧
        left ∈ LocalFiber visible
          ∧
        right ∈ LocalFiber visible := by

  rcases
      ombt_visible_projection_has_residue
    with
      ⟨left, right, hNe, hEquivalent⟩

  refine
    ⟨
      ombtVisibleProjection.observe left,
      left,
      right,
      hNe,
      ?_,
      ?_
    ⟩

  · rfl

  · exact
      hEquivalent.symm

/-
## Escrow resolves the visible fibers
-/

/--
Although visible projection alone is non-injective, the complete
visible-plus-escrow decomposition remains injective.
-/
theorem visible_with_escrow_is_injective :
    Function.Injective
      OMBTProjectionInterface.routedOMBT.decompose := by

  exact
    OMBTProjectionInterface.routedOMBT_decompose_injective

/--
Within one visible local fiber, equality of escrow records forces
equality of the complete source states.
-/
theorem escrow_separates_local_fiber
    {left right :
      MemoryEscrowRouted.CompleteState}
    (hLocal :
      LocallyEquivalent left right)
    (hEscrow :
      OMBTProjectionInterface.routedOMBT.escrow left =
        OMBTProjectionInterface.routedOMBT.escrow right) :
    left =
      right := by

  apply
  OMBTProjectionInterface.Interface.source_eq_of_visible_eq_and_escrow_eq
    OMBTProjectionInterface.routedOMBT

  · exact
      hLocal

  · exact
      hEscrow

/--
Distinct complete states in the same local fiber must carry distinct
escrow records.
-/
theorem distinct_local_states_have_distinct_escrow
    {left right :
      MemoryEscrowRouted.CompleteState}
    (hDistinct :
      left ≠ right)
    (hLocal :
      LocallyEquivalent left right) :
    OMBTProjectionInterface.routedOMBT.escrow left ≠
      OMBTProjectionInterface.routedOMBT.escrow right := by

  intro hEscrow

  exact
    hDistinct
      (
        escrow_separates_local_fiber
          hLocal
          hEscrow
      )

/--
The complete source state is equivalent to a visible local state paired
with its escrow coordinate.
-/
def completeEquivLocalEscrow :
    MemoryEscrowRouted.CompleteState ≃
      MemoryEscrowRouted.VisibleState
        ×
      MemoryEscrowRouted.EscrowRecord :=

  OMBTProjectionInterface.Interface.sourceEquivVisibleEscrow
  OMBTProjectionInterface.routedOMBT

/-
## Local evolution generated by projection
-/

/--
The routed complete Tkairos system equipped with the OMBT visible
projection.
-/
def ombtLocalSystem :
    TkairosLocality.LocalSystem
      MemoryEscrowRouted.CompleteState
      MemoryEscrowRouted.VisibleState where

  tkairos :=
    TkairosLocality.routedTkairos

  projection :=
    ombtVisibleProjection

/--
The OMBT local system is definitionally the established routed local
system.
-/
theorem ombtLocalSystem_eq_routedLocalSystem :
    ombtLocalSystem =
      TkairosLocality.routedLocalSystem := by

  rfl

/--
Complete routed evolution factors through the visible local exchange.
-/
theorem ombt_generates_visible_step :
    ombtLocalSystem.RealizesVisibleStep
      MemoryEscrowRouted.visibleStep := by

  exact
    TkairosLocality.routed_realizes_visibleExchange

/--
Local equivalence is preserved under complete routed evolution.
-/
theorem ombt_local_evolution_is_observation_congruent :
    ombtLocalSystem.ObservationCongruent := by

  exact
    TkairosLocality.routed_observationCongruent

/--
The visible projected history obeys its own local successor recursion.
-/
theorem ombt_visible_history_succ
    (initial :
      MemoryEscrowRouted.CompleteState)
    (n : Nat) :
    ombtLocalSystem.visibleHistory
        initial
        (Nat.succ n) =
      MemoryEscrowRouted.visibleStep
        (
          ombtLocalSystem.visibleHistory
            initial
            n
        ) := by

  exact
    TkairosLocality.routed_visibleHistory_succ
      initial
      n

/--
Complete evolution produces visible local evolution and escrow evolution
in parallel.
-/
theorem locality_and_escrow_evolve_together
    (source :
      MemoryEscrowRouted.CompleteState) :
    OMBTProjectionInterface.routedOMBT.decompose
        (
          MemoryEscrowRouted.completeStep source
        ) =
      (
        MemoryEscrowRouted.visibleStep
          (
            OMBTProjectionInterface.routedOMBT.visible
              source
          ),
        MemoryEscrowRouted.escrowStep
          (
            OMBTProjectionInterface.routedOMBT.escrow
              source
          )
      ) := by

  exact
    OMBTProjectionInterface.routedOMBT_decompose_step
      source

/-
## Developmental interpretation
-/

/--
The complete state contains strictly more information than its visible
local projection, while visible state plus escrow remains complete.
-/
theorem locality_is_projection_not_information_loss :
    ombtVisibleProjection.HasResidue
      ∧
    ¬ Function.Injective ombtVisibleProjection.observe
      ∧
    Function.Injective
      OMBTProjectionInterface.routedOMBT.decompose
      ∧
    (
      ∀ source :
          MemoryEscrowRouted.CompleteState,
        OMBTProjectionInterface.routedOMBT.reconstruct
            (
              OMBTProjectionInterface.routedOMBT.visible
                source,
              OMBTProjectionInterface.routedOMBT.escrow
                source
            ) =
          source
    ) := by

  exact
    ⟨
      ombt_visible_projection_has_residue,
      ombt_visible_projection_not_injective,
      visible_with_escrow_is_injective,
      OMBTProjectionInterface.routedOMBT_reconstructs_complete_state
    ⟩

/-
## Capstone
-/

/--
Capstone theorem.

The OMBT generates a visible locality by identifying complete states
inside observable fibers. These fibers are nontrivial: the visible
projection alone is not injective and therefore omits structured routing
information.

The omitted information is not destroyed. Escrow separates distinct
complete states within each visible fiber, visible-plus-escrow remains
injective, and both components evolve lawfully under routed Tkairos
evolution.

Thus locality first appears as the visible quotient of a complete
pre-local state:

    complete state
          ≃
    local visible state × escrow state.
-/
theorem ombt_locality_emerges :
    ombtVisibleProjection.HasResidue
      ∧
    ¬ Function.Injective
        ombtVisibleProjection.observe
      ∧
    Function.Injective
      OMBTProjectionInterface.routedOMBT.decompose
      ∧
    (
      ∀
        {left right :
          MemoryEscrowRouted.CompleteState},
        LocallyEquivalent left right →
        OMBTProjectionInterface.routedOMBT.escrow left =
          OMBTProjectionInterface.routedOMBT.escrow right →
        left = right
    )
      ∧
    ombtLocalSystem.RealizesVisibleStep
      MemoryEscrowRouted.visibleStep
      ∧
    ombtLocalSystem.ObservationCongruent
      ∧
    (
      ∀ source :
          MemoryEscrowRouted.CompleteState,
        OMBTProjectionInterface.routedOMBT.decompose
            (
              MemoryEscrowRouted.completeStep source
            ) =
          (
            MemoryEscrowRouted.visibleStep
              (
                OMBTProjectionInterface.routedOMBT.visible
                  source
              ),
            MemoryEscrowRouted.escrowStep
              (
                OMBTProjectionInterface.routedOMBT.escrow
                  source
              )
          )
    ) := by

  exact
    ⟨
      ombt_visible_projection_has_residue,
      ombt_visible_projection_not_injective,
      visible_with_escrow_is_injective,
      escrow_separates_local_fiber,
      ombt_generates_visible_step,
      ombt_local_evolution_is_observation_congruent,
      locality_and_escrow_evolve_together
    ⟩

end OMBTLocalityGeneration

#check OMBTLocalityGeneration.ombtVisibleProjection
#check OMBTLocalityGeneration.LocallyEquivalent
#check OMBTLocalityGeneration.LocalFiber
#check OMBTLocalityGeneration.ombt_visible_projection_has_residue
#check OMBTLocalityGeneration.nontrivial_local_fiber_exists
#check OMBTLocalityGeneration.escrow_separates_local_fiber
#check OMBTLocalityGeneration.completeEquivLocalEscrow
#check OMBTLocalityGeneration.ombtLocalSystem
#check OMBTLocalityGeneration.ombt_generates_visible_step
#check OMBTLocalityGeneration.ombt_visible_history_succ
#check OMBTLocalityGeneration.locality_is_projection_not_information_loss
#check OMBTLocalityGeneration.ombt_locality_emerges
