import KTLean.OMBTDirectedEvent
import KTLean.Monad
import Mathlib.Tactic

/-!
# OMBT Emergence of the 168 Monads

## Formal status

**Level 2 — Reconstruction of the monad space from the completed
42-glyph spectrum and the fourfold OMBT directed-event fiber.**

## Developmental predecessor

`OMBTDirectedEvent`

The preceding development establishes two independently forced factors:

* exactly 42 canonical glyphs;
* exactly four directed-information views generated by OMBT projection,
  escrow, and temporal event orientation.

The four views are:

    forward   × visible
    forward   × escrow
    recovered × visible
    recovered × escrow.

A monad is therefore not introduced as a new primitive object. It is one
completed glyph realized through one lawful OMBT directed-information
view:

    Monad ≃ Glyph × DirectedView.

Consequently:

    |Monad| = 42 × 4 = 168.

This module identifies that OMBT-derived product with the existing KT
monad implementation and proves that every glyph carries exactly four
distinct realized monads.
-/

namespace OMBTMonadEmergence

/-
## OMBT monad product
-/

/--
An OMBT monad coordinate is one lawful glyph paired with one directed
projection-and-escrow view.
-/
abbrev OMBTMonadProduct :=
  KTGlyph.Glyph ×
    OMBTDirectedEvent.DirectedView

/--
Construct the existing KT monad represented by one OMBT glyph-view pair.
-/
def realizeMonad
    (data : OMBTMonadProduct) :
    KTMonad.Monad :=

  KTMonad.ofGlyphView
    data.1
    data.2

/--
Recover the glyph-view coordinates of an existing KT monad.
-/
def coordinatesOfMonad
    (monad : KTMonad.Monad) :
    OMBTMonadProduct :=

  KTMonad.toProduct monad

/--
Realizing recovered monad coordinates returns the original monad.
-/
@[simp]
theorem realizeMonad_coordinatesOfMonad
    (monad : KTMonad.Monad) :
    realizeMonad
        (coordinatesOfMonad monad) =
      monad := by

  exact
    KTMonad.ofProduct_toProduct monad

/--
Recovering the coordinates of a realized OMBT monad returns the original
glyph-view pair.
-/
@[simp]
theorem coordinatesOfMonad_realizeMonad
    (data : OMBTMonadProduct) :
    coordinatesOfMonad
        (realizeMonad data) =
      data := by

  exact
    KTMonad.toProduct_ofProduct data

/--
The OMBT glyph-view product is equivalent to the existing monad type.
-/
def ombtMonadEquiv :
    OMBTMonadProduct ≃
      KTMonad.Monad where

  toFun :=
    realizeMonad

  invFun :=
    coordinatesOfMonad

  left_inv :=
    coordinatesOfMonad_realizeMonad

  right_inv :=
    realizeMonad_coordinatesOfMonad

/-
## Four monads over every glyph
-/

/--
The OMBT monads lying over one fixed glyph.
-/
abbrev OMBTMonadsOver
    (glyph : KTGlyph.Glyph) :=
  {
    data : OMBTMonadProduct //
      data.1 = glyph
  }

/--
OMBT monads over one fixed glyph are equivalent to the fourfold directed
view space.
-/
def ombtMonadsOverEquivDirectedView
    (glyph : KTGlyph.Glyph) :
    OMBTMonadsOver glyph ≃
      OMBTDirectedEvent.DirectedView where

  toFun :=
    fun data =>
      data.1.2

  invFun :=
    fun view =>
      ⟨
        (glyph, view),
        rfl
      ⟩

  left_inv := by
    intro data

    rcases data with
      ⟨
        ⟨dataGlyph, view⟩,
        hGlyph
      ⟩

    dsimp at hGlyph
    subst dataGlyph
    rfl

  right_inv := by
    intro view
    rfl

/--
The monads over a fixed glyph form a finite type.
-/
noncomputable instance ombtMonadsOverFintype
    (glyph : KTGlyph.Glyph) :
    Fintype (OMBTMonadsOver glyph) :=

  Fintype.ofEquiv
    OMBTDirectedEvent.DirectedView
    (ombtMonadsOverEquivDirectedView glyph).symm

/--
Every completed glyph carries exactly four OMBT monads.
-/
theorem four_ombt_monads_over_every_glyph
    (glyph : KTGlyph.Glyph) :
    Fintype.card
        (OMBTMonadsOver glyph) =
      4 := by

  rw [
    Fintype.card_congr
      (ombtMonadsOverEquivDirectedView glyph)
  ]

  exact
    DirectedTkairos.view_card

/--
The existing KT monads over every glyph also have cardinality four.
-/
theorem four_existing_monads_over_every_glyph
    (glyph : KTGlyph.Glyph) :
    Fintype.card
        (KTMonad.MonadsOver glyph) =
      4 := by

  exact
    KTMonad.monads_over_glyph_card glyph

/-
## Distinct realization
-/

/--
Realization of OMBT monad coordinates is injective.
-/
theorem realizeMonad_injective :
    Function.Injective realizeMonad := by

  intro left right hEqual

  have hCoordinates :
      coordinatesOfMonad
          (realizeMonad left) =
        coordinatesOfMonad
          (realizeMonad right) :=
    congrArg coordinatesOfMonad hEqual

  simpa using hCoordinates

/--
For one fixed glyph, distinct directed views produce distinct monads.
-/
theorem distinct_views_give_distinct_monads
    (glyph : KTGlyph.Glyph)
    {left right :
      OMBTDirectedEvent.DirectedView}
    (hDistinct :
      left ≠ right) :
    realizeMonad (glyph, left) ≠
      realizeMonad (glyph, right) := by

  intro hEqual

  have hCoordinates :
      (glyph, left) =
        (glyph, right) :=
    realizeMonad_injective hEqual

  exact
    hDistinct
      (
        congrArg Prod.snd hCoordinates
      )

/--
At the concrete moving projected token, realization remains injective
over every fixed glyph.
-/
theorem concrete_realization_injective_over_glyph
    (glyph : KTGlyph.Glyph)
    {left right :
      OMBTDirectedEvent.DirectedView}
    (hRealized :
      OMBTDirectedEvent.realizeProjectedView
          OMBTDirectedEvent.movingProjectedToken
          left =
        OMBTDirectedEvent.realizeProjectedView
          OMBTDirectedEvent.movingProjectedToken
          right) :
    realizeMonad (glyph, left) =
      realizeMonad (glyph, right) := by

  have hView :
      left =
        right :=
    OMBTDirectedEvent.concrete_realizeProjectedView_injective
      hRealized

  rw [hView]

/--
The four OMBT views are concretely distinct and therefore provide four
distinct monadic realizations over every glyph.
-/
theorem four_distinct_realized_monads_over_every_glyph
    (glyph : KTGlyph.Glyph) :
    Fintype.card
        (OMBTMonadsOver glyph) =
      4
      ∧
    Function.Injective
      (
        fun view :
          OMBTDirectedEvent.DirectedView =>
          realizeMonad (glyph, view)
      )
      ∧
    Function.Injective
      (
        OMBTDirectedEvent.realizeProjectedView
          OMBTDirectedEvent.movingProjectedToken
      ) := by

  refine
    ⟨
      four_ombt_monads_over_every_glyph glyph,
      ?_,
      OMBTDirectedEvent.concrete_realizeProjectedView_injective
    ⟩

  intro left right hEqual

  have hCoordinates :
      (glyph, left) =
        (glyph, right) :=
    realizeMonad_injective hEqual

  exact
    congrArg Prod.snd hCoordinates

/-
## Total monad cardinality
-/

/--
The OMBT monad product has exactly 168 elements.
-/
theorem card_ombtMonadProduct :
    Fintype.card OMBTMonadProduct =
      168 := by

  change
    Fintype.card
        (
          KTGlyph.Glyph ×
            OMBTDirectedEvent.DirectedView
        ) =
      168

  rw [
    Fintype.card_prod,
    KTGlyph.card_glyph,
    DirectedTkairos.view_card
  ]

/--
The OMBT monad count factors as 42 glyphs times four directed views.
-/
theorem card_ombtMonadProduct_factorization :
    Fintype.card OMBTMonadProduct =
      42 * 4 := by

  rw [
    card_ombtMonadProduct
  ]

/--
The OMBT monad product and the existing monad type have the same
cardinality.
-/
theorem card_existing_monad_from_ombt :
    Fintype.card KTMonad.Monad =
      Fintype.card OMBTMonadProduct := by

  exact
    Fintype.card_congr
      ombtMonadEquiv.symm

/--
The existing KT monad space contains exactly 168 elements because it is
equivalent to the OMBT-derived glyph-view product.
-/
theorem existing_monad_card_from_ombt :
    Fintype.card KTMonad.Monad =
      168 := by

  calc
    Fintype.card KTMonad.Monad =
        Fintype.card OMBTMonadProduct :=
      card_existing_monad_from_ombt

    _ =
        168 :=
      card_ombtMonadProduct

/-
## Developmental provenance
-/

/--
The two factors entering monad emergence have independent formal
provenance:

* the canonical spectrum contains exactly 42 glyphs;
* OMBT projection and directed escrow dynamics produce exactly four
  views.
-/
theorem monad_factors_emerge_independently :
    Fintype.card KTGlyph.Glyph =
        42
      ∧
    Fintype.card
        OMBTDirectedEvent.DirectedView =
        4
      ∧
    DirectedTkairosWitness.realizedViews.card =
        4 := by

  exact
    ⟨
      KTGlyph.card_glyph,
      DirectedTkairos.view_card,
      OMBTDirectedEvent.realized_projected_views_card
    ⟩

/--
The completed canonical spectrum precedes the monad multiplication.
-/
theorem complete_glyph_spectrum_precedes_monads :
    GlyphSpectralCompleteEmergence.emergentSpectrum =
        GlyphSpectrum.values
      ∧
    GlyphSpectrum.values.length =
        42 := by

  exact
    ⟨
      GlyphSpectralCompleteEmergence.emergentSpectrum_eq_canonical,
      GlyphSpectrum.values_length
    ⟩

/-
## Capstone
-/

/--
Capstone theorem.

The completed pre-geometric spectrum supplies exactly 42 glyphs. OMBT
projection with escrow generates locality, directed temporal orientation,
and exactly four distinct information views. Pairing each lawful glyph
with one such realized view produces the monad space.

The resulting product is equivalent to the existing KT monad
implementation, every glyph carries exactly four monads, and the complete
monad space contains exactly:

    42 × 4 = 168.

Thus the 168 monads emerge from the independently derived glyph alphabet
and the OMBT fourfold event fiber rather than from an imposed numerical
definition.
-/
theorem ombt_monads_emerge :
    (
      GlyphSpectralCompleteEmergence.emergentSpectrum =
          GlyphSpectrum.values
        ∧
      Fintype.card KTGlyph.Glyph =
          42
    )
      ∧
    (
      Fintype.card
          OMBTDirectedEvent.DirectedView =
          4
        ∧
      Function.Injective
        (
          OMBTDirectedEvent.realizeProjectedView
            OMBTDirectedEvent.movingProjectedToken
        )
        ∧
      DirectedTkairosWitness.realizedViews.card =
          4
    )
      ∧
    (
      ∀ glyph : KTGlyph.Glyph,
        Fintype.card
            (OMBTMonadsOver glyph) =
          4
    )
      ∧
    (
      Nonempty (OMBTMonadProduct ≃
        KTMonad.Monad)
    )
      ∧
    Fintype.card OMBTMonadProduct =
      42 * 4
      ∧
    Fintype.card KTMonad.Monad =
      168 := by

  exact
    ⟨
      ⟨
        GlyphSpectralCompleteEmergence.emergentSpectrum_eq_canonical,
        KTGlyph.card_glyph
      ⟩,
      ⟨
        DirectedTkairos.view_card,
        OMBTDirectedEvent.concrete_realizeProjectedView_injective,
        OMBTDirectedEvent.realized_projected_views_card
      ⟩,
      four_ombt_monads_over_every_glyph,
      ⟨ombtMonadEquiv⟩,
      card_ombtMonadProduct_factorization,
      existing_monad_card_from_ombt
    ⟩

end OMBTMonadEmergence

#check OMBTMonadEmergence.OMBTMonadProduct
#check OMBTMonadEmergence.realizeMonad
#check OMBTMonadEmergence.ombtMonadEquiv
#check OMBTMonadEmergence.OMBTMonadsOver
#check OMBTMonadEmergence.four_ombt_monads_over_every_glyph
#check OMBTMonadEmergence.realizeMonad_injective
#check OMBTMonadEmergence.four_distinct_realized_monads_over_every_glyph
#check OMBTMonadEmergence.card_ombtMonadProduct
#check OMBTMonadEmergence.existing_monad_card_from_ombt
#check OMBTMonadEmergence.monad_factors_emerge_independently
#check OMBTMonadEmergence.ombt_monads_emerge
