import KTLean.PascalForcingBinomialIdentification

/-!
# Pascal Modulo Three Forcing Capstone

## Formal status

**Level 2 — Consequence of the explicit triadic additive structure,
the single positive seed, inactive boundary convention, and local
two-parent propagation rule.**

The forcing chain established in the preceding modules is:

    triadic control alphabet
        ↓
    closed balanced addition
        ↓
    canonical residues modulo three
        ↓
    single-seed two-parent propagation
        ↓
    unique global triangular field
        ↓
    binomial coefficients reduced modulo three.

This module packages the principal conclusion:

Every field satisfying the seed and local two-parent propagation
specification is exactly the existing `PascalMod3.control` field.

Thus Pascal modulo three is not introduced as an independent geometric
choice. It is identified as the unique global solution generated by
the stated local additive dynamics.
-/

namespace PascalForcingCapstone

open PascalMod3
open PascalForcingPropagation
open PascalForcingPropagationUniqueness
open PascalForcingBinomialIdentification

/--
Every field satisfying the triadic propagation specification equals
the existing Pascal modulo-three control field.
-/
theorem any_admissible_field_eq_pascal
    (field : Nat → Nat → Control)
    (hField : SatisfiesPropagation field) :
    field =
      PascalMod3.control := by

  calc
    field =
        propagate := by
      exact
        field_eq_propagate
          field
          hField

    _ =
        PascalMod3.control := by
      funext rowIndex position

      exact
        propagate_eq_existing_control
          rowIndex
          position

/--
Any two fields satisfying the triadic propagation specification are
equal because both are the Pascal modulo-three field.
-/
theorem admissible_fields_unique
    (firstField secondField : Nat → Nat → Control)
    (hFirst : SatisfiesPropagation firstField)
    (hSecond : SatisfiesPropagation secondField) :
    firstField =
      secondField := by

  calc
    firstField =
        PascalMod3.control := by
      exact
        any_admissible_field_eq_pascal
          firstField
          hFirst

    _ =
        secondField := by
      exact
        (
          any_admissible_field_eq_pascal
            secondField
            hSecond
        ).symm

/--
The existing Pascal modulo-three field satisfies the propagation
specification.
-/
theorem pascal_control_satisfies :
    SatisfiesPropagation
      PascalMod3.control := by

  have hControl :
      PascalMod3.control =
        propagate := by

    funext rowIndex position

    exact
      (
        propagate_eq_existing_control
          rowIndex
          position
      ).symm

  rw [hControl]

  exact
    propagate_satisfies

/--
There exists exactly one field satisfying the propagation
specification, and that field is the existing Pascal modulo-three
control field.
-/
theorem existsUnique_pascal_control :
    ∃! field : Nat → Nat → Control,
      SatisfiesPropagation field := by

  refine
    ⟨
      PascalMod3.control,
      pascal_control_satisfies,
      ?_
    ⟩

  intro field hField

  exact
    any_admissible_field_eq_pascal
      field
      hField

/--
Pointwise form of the forcing theorem.

At every address, any admissible field equals the Pascal coefficient
reduced modulo three and interpreted as a triadic control state.
-/
theorem admissible_value_eq_pascal
    (field : Nat → Nat → Control)
    (hField : SatisfiesPropagation field)
    (rowIndex position : Nat) :
    field rowIndex position =
      PascalMod3.control
        rowIndex
        position := by

  have hEquality :
      field =
        PascalMod3.control :=
    any_admissible_field_eq_pascal
      field
      hField

  exact
    congrFun
      (
        congrFun
          hEquality
          rowIndex
      )
      position

/--
Pointwise binomial form of the forcing theorem.

Every admissible value is the canonical triadic decoding of the
corresponding binomial coefficient.
-/
theorem admissible_value_eq_decode_choose
    (field : Nat → Nat → Control)
    (hField : SatisfiesPropagation field)
    (rowIndex position : Nat) :
    field rowIndex position =
      PascalForcingTriadicResidues.decode
        (
          Nat.choose
            rowIndex
            position
        ) := by

  calc
    field rowIndex position =
        PascalMod3.control
          rowIndex
          position := by
      exact
        admissible_value_eq_pascal
          field
          hField
          rowIndex
          position

    _ =
        PascalForcingTriadicResidues.decode
          (
            Nat.choose
              rowIndex
              position
          ) := by
      exact
        PascalForcingExistingControlBridge.control_eq_decode_choose
          rowIndex
          position

end PascalForcingCapstone

#check PascalForcingCapstone.any_admissible_field_eq_pascal
#check PascalForcingCapstone.admissible_fields_unique
#check PascalForcingCapstone.pascal_control_satisfies
#check PascalForcingCapstone.existsUnique_pascal_control
#check PascalForcingCapstone.admissible_value_eq_pascal
#check PascalForcingCapstone.admissible_value_eq_decode_choose
