import Mathlib.Algebra.Quaternion
import KTLean.MemoryEscrow

/-!
# Quaternion Reversibility

This module supplies the first nontrivial concrete witness
of reversible multiplication in KTLean.

For a nonzero quaternion `a`, forward evolution is

    x ↦ a * x

and recovery is explicitly

    y ↦ a⁻¹ * y.

Unlike the abstract finite-dimensional inverse constructed
in `Composition.lean`, this recovery map is given directly
by quaternion inversion.

Mathlib defines quaternion inversion through conjugation
and norm-square:

    a⁻¹ = (normSq a)⁻¹ • star a.
-/

open scoped Quaternion

universe u


namespace QuaternionWitness


variable {R : Type u}
variable [Field R]
variable [LinearOrder R]
variable [IsStrictOrderedRing R]


/--
Left multiplication by a nonzero quaternion, equipped
with its explicit inverse recovery operation.
-/
def leftMulReversibleStep
    {a : ℍ[R]}
    (ha : a ≠ 0) :
    ReversibleStep ℍ[R] where

  step := fun x => a * x

  recover := fun y => a⁻¹ * y

  recover_step := by
    intro x
    rw [← mul_assoc, inv_mul_cancel₀ ha, one_mul]

  step_recover := by
    intro y
    rw [← mul_assoc, mul_inv_cancel₀ ha, one_mul]


/--
The forward operation is quaternion left multiplication.
-/
@[simp]
theorem leftMulReversibleStep_step
    {a : ℍ[R]}
    (ha : a ≠ 0)
    (x : ℍ[R]) :
    (leftMulReversibleStep ha).step x =
      a * x := by

  rfl


/--
Recovery is multiplication on the left by the quaternion inverse.
-/
@[simp]
theorem leftMulReversibleStep_recover
    {a : ℍ[R]}
    (ha : a ≠ 0)
    (y : ℍ[R]) :
    (leftMulReversibleStep ha).recover y =
      a⁻¹ * y := by

  rfl


/--
Quaternion recovery written explicitly through norm-square
and conjugation.
-/
theorem leftMulReversibleStep_recover_formula
    {a : ℍ[R]}
    (ha : a ≠ 0)
    (y : ℍ[R]) :
    (leftMulReversibleStep ha).recover y =
      ((Quaternion.normSq a)⁻¹ • star a) * y := by

  change a⁻¹ * y =
    ((Quaternion.normSq a)⁻¹ • star a) * y

  rw [Quaternion.inv_def]


/--
The Peano-indexed history generated by repeated
left multiplication by a nonzero quaternion.
-/
def leftMulHistory
    {a : ℍ[R]}
    (ha : a ≠ 0)
    (initial : ℍ[R]) :
    Nat → ℍ[R] :=

  ReversibleStep.history
    (leftMulReversibleStep ha)
    initial


/--
Each successor state is generated by left multiplication
by the fixed quaternion `a`.
-/
@[simp]
theorem leftMulHistory_succ
    {a : ℍ[R]}
    (ha : a ≠ 0)
    (initial : ℍ[R])
    (n : Nat) :
    leftMulHistory ha initial (Nat.succ n) =
      a * leftMulHistory ha initial n := by

  rfl


/--
One application of explicit quaternion recovery reconstructs
the immediately preceding state.
-/
theorem leftMulHistory_recovers_previous
    {a : ℍ[R]}
    (ha : a ≠ 0)
    (initial : ℍ[R])
    (n : Nat) :
    (leftMulReversibleStep ha).recover
        (leftMulHistory ha initial (Nat.succ n)) =
      leftMulHistory ha initial n := by

  simpa [leftMulHistory] using
    ReversibleStep.history_recovers_previous
      (leftMulReversibleStep ha)
      initial
      n


/--
Repeated quaternion recovery reconstructs a state lying
any finite number of transitions in the past.
-/
theorem leftMulHistory_recovers_after
    {a : ℍ[R]}
    (ha : a ≠ 0)
    (initial : ℍ[R])
    (n k : Nat) :
    ReversibleStep.recoverN
        (leftMulReversibleStep ha)
        k
        (leftMulHistory ha initial (n + k)) =
      leftMulHistory ha initial n := by

  simpa [leftMulHistory] using
    ReversibleStep.history_recovers_after
      (leftMulReversibleStep ha)
      initial
      n
      k


end QuaternionWitness


#check QuaternionWitness.leftMulReversibleStep
#check QuaternionWitness.leftMulReversibleStep_step
#check QuaternionWitness.leftMulReversibleStep_recover
#check QuaternionWitness.leftMulReversibleStep_recover_formula
#check QuaternionWitness.leftMulHistory
#check QuaternionWitness.leftMulHistory_succ
#check QuaternionWitness.leftMulHistory_recovers_previous
#check QuaternionWitness.leftMulHistory_recovers_after
