import KTLean.Transition
import KTLean.Evolution

/-!
General reversible dynamics and memory recovery in Kosmoplex Theory.

A reversible transition carries both:

* a forward state transformation,
* a recovery transformation that reconstructs the prior state.

This module abstracts the memory-recovery result first observed
in the concrete Flux dynamics.
-/

universe u


/--
A reversible state transition.

`step` advances the state.

`recover` reconstructs the prior state.

The two inverse laws guarantee that neither direction
loses information.
-/
structure ReversibleStep (State : Type u) where
  step : State → State
  recover : State → State

  recover_step :
    ∀ state : State,
      recover (step state) = state

  step_recover :
    ∀ state : State,
      step (recover state) = state


namespace ReversibleStep


/--
The transition law generated by a reversible step.
-/
def law
    {State : Type u}
    (r : ReversibleStep State) :
    TransitionLaw State :=
  graphLaw r.step


/--
Every reversible step has a constructive realization.
-/
def realization
    {State : Type u}
    (r : ReversibleStep State) :
    Realization (law r) :=
  graphRealization r.step


/--
When state equality is decidable, every reversible step
also has a decidable realization.
-/
def decidableRealization
    {State : Type u}
    [DecidableEq State]
    (r : ReversibleStep State) :
    DecidableRealization (law r) :=
  graphDecidableRealization r.step


/--
A reversible transition is injective.

No two prior states can produce the same successor state.
-/
theorem step_injective
    {State : Type u}
    (r : ReversibleStep State) :
    Function.Injective r.step := by
  intro a b hab

  calc
    a = r.recover (r.step a) := (r.recover_step a).symm
    _ = r.recover (r.step b) := congrArg r.recover hab
    _ = b := r.recover_step b


/--
A reversible transition is surjective.

Every state has at least one predecessor.
-/
theorem step_surjective
    {State : Type u}
    (r : ReversibleStep State) :
    Function.Surjective r.step := by
  intro target
  exact ⟨r.recover target, r.step_recover target⟩


/--
A reversible transition is both injective and surjective.
-/
theorem step_bijective
    {State : Type u}
    (r : ReversibleStep State) :
    Function.Injective r.step ∧
    Function.Surjective r.step := by
  exact ⟨step_injective r, step_surjective r⟩


/--
A reversible transition law is total and functional.
-/
theorem law_totalFunctional
    {State : Type u}
    (r : ReversibleStep State) :
    TotalFunctional (law r) := by
  exact realization_is_totalFunctional
    (realization r).realizes


/--
The Peano-indexed history generated by a reversible step.
-/
def history
    {State : Type u}
    (r : ReversibleStep State)
    (initial : State) :
    Nat → State :=
  stateHistory r.step initial


@[simp]
theorem history_zero
    {State : Type u}
    (r : ReversibleStep State)
    (initial : State) :
    history r initial 0 = initial := by
  rfl


@[simp]
theorem history_succ
    {State : Type u}
    (r : ReversibleStep State)
    (initial : State)
    (n : Nat) :
    history r initial (Nat.succ n) =
      r.step (history r initial n) := by
  rfl


/--
The prior entry in a reversible history can be recovered
from the following entry.

This is the general formal statement of one-step
memory escrow.
-/
theorem history_recovers_previous
    {State : Type u}
    (r : ReversibleStep State)
    (initial : State)
    (n : Nat) :
    r.recover (history r initial (Nat.succ n)) =
      history r initial n := by
  change
    r.recover
        (r.step (stateHistory r.step initial n)) =
      stateHistory r.step initial n

  exact r.recover_step
    (stateHistory r.step initial n)


/--
An involution canonically defines a reversible transition.

When applying `step` twice restores the original state,
the forward and recovery operations are the same function.
-/
def ofInvolution
    {State : Type u}
    (step : State → State)
    (hinvolution :
      ∀ state : State,
        step (step state) = state) :
    ReversibleStep State where

  step := step
  recover := step
  recover_step := hinvolution
  step_recover := hinvolution


end ReversibleStep


#check ReversibleStep
#check ReversibleStep.law
#check ReversibleStep.realization
#check ReversibleStep.decidableRealization
#check ReversibleStep.step_injective
#check ReversibleStep.step_surjective
#check ReversibleStep.step_bijective
#check ReversibleStep.law_totalFunctional
#check ReversibleStep.history
#check ReversibleStep.history_recovers_previous
#check ReversibleStep.ofInvolution
