import KTLean.SevenForcingCapstone

/-!
# Noncollinear Frames in Seven-Forcing Systems

## Formal status

**Level 2 — Consequence of nondegeneracy.**

A nondegenerate global triadic-closure system contains:

* two distinct points `x` and `y`;
* a point `p` outside the block generated by `x` and `y`.

Writing

    z = complete x y,

the four points

    x, y, z, p

are distinct in the required structural sense.

This module packages such data as a frame. It does not assume that the
carrier has seven points and does not yet identify the system with the
explicit Fano plane.
-/

namespace SevenForcingFanoFrame

universe u

variable {Point : Type u}
variable [DecidableEq Point]

/--
A raw candidate frame consists of three selected points.
-/
abbrev RawFrame :=
  Point × Point × Point

/--
A raw triple `(x,y,p)` is a noncollinear frame when `x ≠ y` and `p`
lies outside the block generated by `x` and `y`.
-/
def IsFrame
    (S : SevenForcing.GlobalTriadicClosure Point)
    (frame : RawFrame (Point := Point)) :
    Prop :=
  frame.1 ≠ frame.2.1 ∧
    frame.2.2 ∉
      S.block frame.1 frame.2.1

/--
The type of noncollinear frames in a selected global triadic-closure
system.
-/
abbrev Frame
    (S : SevenForcing.GlobalTriadicClosure Point) :=
  {
    frame : RawFrame (Point := Point) //
      IsFrame S frame
  }

/--
The first selected point of a frame.
-/
def Frame.first
    {S : SevenForcing.GlobalTriadicClosure Point}
    (frame : Frame S) :
    Point :=
  frame.1.1

/--
The second selected point of a frame.
-/
def Frame.second
    {S : SevenForcing.GlobalTriadicClosure Point}
    (frame : Frame S) :
    Point :=
  frame.1.2.1

/--
The external point of a frame.
-/
def Frame.external
    {S : SevenForcing.GlobalTriadicClosure Point}
    (frame : Frame S) :
    Point :=
  frame.1.2.2

/--
The third point on the line generated by the first two frame points.
-/
def Frame.lineThird
    {S : SevenForcing.GlobalTriadicClosure Point}
    (frame : Frame S) :
    Point :=
  S.complete frame.first frame.second

/--
The first two frame points are distinct.
-/
theorem Frame.first_ne_second
    {S : SevenForcing.GlobalTriadicClosure Point}
    (frame : Frame S) :
    frame.first ≠ frame.second := by

  exact frame.2.1

/--
The external frame point lies outside the block generated by the first
two points.
-/
theorem Frame.external_not_mem_block
    {S : SevenForcing.GlobalTriadicClosure Point}
    (frame : Frame S) :
    frame.external ∉
      S.block frame.first frame.second := by

  exact frame.2.2

/--
The external point differs from the first frame point.
-/
theorem Frame.external_ne_first
    {S : SevenForcing.GlobalTriadicClosure Point}
    (frame : Frame S) :
    frame.external ≠ frame.first := by

  intro h

  apply frame.external_not_mem_block

  rw [h]

  exact
    S.left_mem_block
      frame.first
      frame.second

/--
The external point differs from the second frame point.
-/
theorem Frame.external_ne_second
    {S : SevenForcing.GlobalTriadicClosure Point}
    (frame : Frame S) :
    frame.external ≠ frame.second := by

  intro h

  apply frame.external_not_mem_block

  rw [h]

  exact
    S.right_mem_block
      frame.first
      frame.second

/--
The line-completion point differs from the first frame point.
-/
theorem Frame.lineThird_ne_first
    {S : SevenForcing.GlobalTriadicClosure Point}
    (frame : Frame S) :
    frame.lineThird ≠ frame.first := by

  exact
    S.complete_ne_left
      frame.first_ne_second

/--
The line-completion point differs from the second frame point.
-/
theorem Frame.lineThird_ne_second
    {S : SevenForcing.GlobalTriadicClosure Point}
    (frame : Frame S) :
    frame.lineThird ≠ frame.second := by

  exact
    S.complete_ne_right
      frame.first_ne_second

/--
The external point differs from the third point on the generated line.
-/
theorem Frame.external_ne_lineThird
    {S : SevenForcing.GlobalTriadicClosure Point}
    (frame : Frame S) :
    frame.external ≠ frame.lineThird := by

  intro h

  apply frame.external_not_mem_block

  rw [h]

  exact
    S.completion_mem_block
      frame.first
      frame.second

/--
The four points `first`, `second`, `lineThird`, and `external` satisfy
the expected distinctness relations.
-/
theorem Frame.four_point_distinctness
    {S : SevenForcing.GlobalTriadicClosure Point}
    (frame : Frame S) :
    frame.first ≠ frame.second
      ∧ frame.lineThird ≠ frame.first
      ∧ frame.lineThird ≠ frame.second
      ∧ frame.external ≠ frame.first
      ∧ frame.external ≠ frame.second
      ∧ frame.external ≠ frame.lineThird := by

  exact
    ⟨
      frame.first_ne_second,
      frame.lineThird_ne_first,
      frame.lineThird_ne_second,
      frame.external_ne_first,
      frame.external_ne_second,
      frame.external_ne_lineThird
    ⟩

/--
Every nondegenerate global triadic-closure system contains a
noncollinear frame.
-/
theorem exists_frame
    (S : SevenForcing.GlobalTriadicClosure Point)
    (hNondegenerate : SevenForcing.Nondegenerate S) :
    Nonempty (Frame S) := by

  rcases
    SevenForcing.exists_external_point
      hNondegenerate
    with ⟨x, y, p, hxy, hp⟩

  exact
    ⟨
      ⟨
        (x, y, p),
        ⟨hxy, hp⟩
      ⟩
    ⟩

end SevenForcingFanoFrame

#check SevenForcingFanoFrame.RawFrame
#check SevenForcingFanoFrame.IsFrame
#check SevenForcingFanoFrame.Frame
#check SevenForcingFanoFrame.Frame.first
#check SevenForcingFanoFrame.Frame.second
#check SevenForcingFanoFrame.Frame.external
#check SevenForcingFanoFrame.Frame.lineThird
#check SevenForcingFanoFrame.Frame.four_point_distinctness
#check SevenForcingFanoFrame.exists_frame
