import KTLean.SevenForcingOrbit

/-!
# Cardinality of Complement-Completion Orbits

## Formal status

**Level 2 — Consequence of global triadic closure.**

For a chosen point `x`, every point in the complement belongs to the
two-element orbit

    {y, partner y}.

This module proves that equality of orbit classes is equivalent to
membership in that explicit two-point finset, and therefore every such
orbit has cardinality two.

No global parity or cardinality conclusion is made here.
-/

namespace SevenForcingOrbitCardinality

universe u

variable {Point : Type u}

/--
The explicit two-point orbit generated by a complement point.
-/
def orbitFinset
    [DecidableEq Point]
    (S : SevenForcing.GlobalTriadicClosure Point)
    (x : Point)
    (y : SevenForcingPairing.PointComplement x) :
    Finset (SevenForcingPairing.PointComplement x) :=
  {y, SevenForcingOrbit.partner S x y}

/--
A complement point belongs to the explicit orbit of `y` exactly when
its quotient class equals the quotient class of `y`.
-/
theorem mem_orbitFinset_iff
    [DecidableEq Point]
    (S : SevenForcing.GlobalTriadicClosure Point)
    (x : Point)
    (y z : SevenForcingPairing.PointComplement x) :
    z ∈ orbitFinset S x y
      ↔
    SevenForcingOrbit.orbitOf S x y =
      SevenForcingOrbit.orbitOf S x z := by

  rw [
    SevenForcingOrbit.orbitOf_eq_iff
  ]

  simp [
    orbitFinset,
    SevenForcingOrbit.OrbitRel
  ]

/--
The two entries in the explicit orbit are distinct.
-/
theorem partner_ne
    [DecidableEq Point]
    (S : SevenForcing.GlobalTriadicClosure Point)
    (x : Point)
    (y : SevenForcingPairing.PointComplement x) :
    SevenForcingOrbit.partner S x y ≠ y := by

  exact
    SevenForcingPairing.complementCompletionEquiv_fixedPointFree
      S
      x
      y

/--
Every explicit complement-completion orbit has exactly two elements.
-/
theorem orbitFinset_card
    [DecidableEq Point]
    (S : SevenForcing.GlobalTriadicClosure Point)
    (x : Point)
    (y : SevenForcingPairing.PointComplement x) :
    (orbitFinset S x y).card = 2 := by

  have hyPartner :
      y ≠ SevenForcingOrbit.partner S x y :=
    Ne.symm (partner_ne S x y)

  simp [
    orbitFinset,
    hyPartner
  ]

/--
Two points generate the same explicit orbit exactly when their quotient
classes agree.
-/
theorem orbitFinset_eq_of_orbitOf_eq
    [DecidableEq Point]
    (S : SevenForcing.GlobalTriadicClosure Point)
    (x : Point)
    {y z : SevenForcingPairing.PointComplement x}
    (h :
      SevenForcingOrbit.orbitOf S x y =
        SevenForcingOrbit.orbitOf S x z) :
    orbitFinset S x y =
      orbitFinset S x z := by

  ext w

  rw [
    mem_orbitFinset_iff,
    mem_orbitFinset_iff
  ]

  constructor

  · intro hyw
    exact h.symm.trans hyw

  · intro hzw
    exact h.trans hzw

end SevenForcingOrbitCardinality

#check SevenForcingOrbitCardinality.orbitFinset
#check SevenForcingOrbitCardinality.mem_orbitFinset_iff
#check SevenForcingOrbitCardinality.partner_ne
#check SevenForcingOrbitCardinality.orbitFinset_card
#check SevenForcingOrbitCardinality.orbitFinset_eq_of_orbitOf_eq
