import KTLean.SevenForcingPairOrbitQuotient

/-!
# Uniform Fibers of the Pair-Orbit Quotient

## Formal status

**Level 2 — Consequence of global triadic closure.**

Every quotient class of distinct ordered pairs is represented by some
pair. The fiber over that class is therefore equivalent to the
rotation–reversal orbit generated by a representative and has natural
cardinality six.

The full distinct-pair carrier also decomposes canonically as the
dependent sum of all quotient fibers:

    DistinctPair ≃ Σ q : PairOrbitQuotient S, PairOrbitFiber S q.

This is the global partition required for the subsequent divisibility
argument.

No minimality assumption and no cardinality-seven conclusion enters
this module.
-/

namespace SevenForcingPairOrbitFiberUniform

noncomputable section

universe u

variable {Point : Type u}

open SevenForcingDistinctPairs
open SevenForcingPairOrbitQuotient

/--
Every quotient class is represented by a distinct ordered pair.
-/
theorem pairOrbitClass_surjective
    (S : SevenForcing.GlobalTriadicClosure Point) :
    Function.Surjective
      (pairOrbitClass S) := by

  intro orbitClass

  refine Quotient.inductionOn orbitClass ?_

  intro pair

  exact ⟨pair, rfl⟩

/--
Every quotient fiber has natural cardinality six.
-/
theorem natCard_pairOrbitFiber_all
    (S : SevenForcing.GlobalTriadicClosure Point)
    (orbitClass : PairOrbitQuotient S) :
    Nat.card (PairOrbitFiber S orbitClass) =
      6 := by

  refine Quotient.inductionOn orbitClass ?_

  intro seed

  exact
    SevenForcingPairOrbitQuotient.natCard_pairOrbitFiber
      S
      seed

/--
Map a distinct ordered pair to its quotient class together with its
membership in the corresponding quotient fiber.
-/
def distinctPairToSigmaFiber
    (S : SevenForcing.GlobalTriadicClosure Point)
    (pair : DistinctPair (Point := Point)) :
    Σ orbitClass : PairOrbitQuotient S,
      PairOrbitFiber S orbitClass :=

  ⟨
    pairOrbitClass S pair,
    ⟨pair, rfl⟩
  ⟩

/--
Forget the quotient-class coordinate and recover the underlying
distinct ordered pair.
-/
def sigmaFiberToDistinctPair
    (S : SevenForcing.GlobalTriadicClosure Point) :
    (
      Σ orbitClass : PairOrbitQuotient S,
        PairOrbitFiber S orbitClass
    ) →
      DistinctPair (Point := Point)

  | ⟨_orbitClass, pair⟩ =>
      pair.1

/--
The full distinct-pair carrier is equivalent to the dependent sum of
all quotient fibers.
-/
def distinctPairEquivSigmaFiber
    (S : SevenForcing.GlobalTriadicClosure Point) :
    DistinctPair (Point := Point) ≃
      Σ orbitClass : PairOrbitQuotient S,
        PairOrbitFiber S orbitClass where

  toFun :=
    distinctPairToSigmaFiber S

  invFun :=
    sigmaFiberToDistinctPair S

  left_inv := by
    intro pair
    rfl

  right_inv := by
    intro fiberPair

    rcases fiberPair with
      ⟨orbitClass, ⟨pair, hclass⟩⟩

    cases hclass

    rfl

end

end SevenForcingPairOrbitFiberUniform

#check SevenForcingPairOrbitFiberUniform.pairOrbitClass_surjective
#check SevenForcingPairOrbitFiberUniform.natCard_pairOrbitFiber_all
#check SevenForcingPairOrbitFiberUniform.distinctPairToSigmaFiber
#check SevenForcingPairOrbitFiberUniform.sigmaFiberToDistinctPair
#check SevenForcingPairOrbitFiberUniform.distinctPairEquivSigmaFiber
