import KTLean.Steiner
import Mathlib.Data.Fintype.Card

/-!
# Seven Forcing from Global Triadic Closure

This module begins the formal derivation of the least nondegenerate
finite global triadic-closure geometry.

## Formal status

**Level 1 — Admissibility interface.**

A global triadic-closure system is represented algebraically by a
Steiner triple system:

    complete : Point → Point → Point

satisfying:

1. `complete x x = x`;
2. `complete x y = complete y x`;
3. `complete x (complete x y) = y`.

For distinct `x,y`, the generated block

    {x, y, complete x y}

has exactly three points.

The crucial nondegeneracy condition is not stated by cardinality.
Instead, it requires that at least one point lies outside at least one
generated triad. Thus the geometry is not exhausted by a single closed
three-point block.

This file does not yet prove that the least such finite system has
seven points. It first isolates the admissibility conditions and proves
that nondegeneracy forces strictly more than three points.
-/

namespace SevenForcing

universe u

/--
A finite global triadic-closure geometry.

This is an alias for the existing algebraic Steiner triple-system
interface. No Fano structure or cardinality is assumed.
-/
abbrev GlobalTriadicClosure
    (Point : Type u) :=
  Steiner.TripleSystem Point

/--
A global triadic-closure geometry is nondegenerate when some point lies
outside the triad generated by some distinct pair.

This excludes the isolated three-point system without mentioning seven
or imposing a cardinal lower bound directly.
-/
def Nondegenerate
    {Point : Type u}
    [DecidableEq Point]
    (S : GlobalTriadicClosure Point) :
    Prop :=
  ∃ x y p : Point,
    x ≠ y ∧
    p ∉ S.block x y

/--
Nondegeneracy supplies a distinct pair and a point outside its generated
three-point block.
-/
theorem exists_external_point
    {Point : Type u}
    [DecidableEq Point]
    {S : GlobalTriadicClosure Point}
    (hS : Nondegenerate S) :
    ∃ x y p : Point,
      x ≠ y ∧
      p ∉ S.block x y := by
  exact hS

/--
A nondegenerate finite global triadic-closure geometry has strictly more
than three points.

This is the first genuine cardinal consequence, and it does not assume
or mention seven.
-/
theorem three_lt_card
    {Point : Type u}
    [Fintype Point]
    [DecidableEq Point]
    {S : GlobalTriadicClosure Point}
    (hS : Nondegenerate S) :
    3 < Fintype.card Point := by

  rcases hS with
    ⟨x, y, p, hxy, hp⟩

  have hblockCard :
      (S.block x y).card = 3 :=
    S.card_block_of_ne hxy

  have hsubset :
      S.block x y ⊆ Finset.univ :=
    Finset.subset_univ _

  have hne :
      S.block x y ≠ Finset.univ := by
    intro hEq

    have hpUniv :
        p ∈ (Finset.univ : Finset Point) := by
      simp

    have hpBlock :
        p ∈ S.block x y := by
      rw [hEq]
      exact hpUniv

    exact hp hpBlock

  have hproper :
      S.block x y ⊂
        (Finset.univ : Finset Point) :=
    (Finset.ssubset_iff_subset_ne).2
      ⟨hsubset, hne⟩

  have hcard :
      (S.block x y).card <
        (Finset.univ : Finset Point).card :=
    Finset.card_lt_card hproper

  simpa [hblockCard] using hcard

end SevenForcing

#check SevenForcing.GlobalTriadicClosure
#check SevenForcing.Nondegenerate
#check SevenForcing.exists_external_point
#check SevenForcing.three_lt_card
