import KTLean.SevenForcingPairOrbitDistinct

/-!
# Cardinality of Rotation–Reversal Pair Orbits

## Formal status

**Level 2 — Consequence of global triadic closure.**

Every rotation–reversal orbit of a distinct ordered pair has exactly
six elements.

The normal-form theorem proves that every orbit element is represented
by one of six canonical positions. The distinctness theorem proves
that these six positions represent different ordered pairs. Together
they yield an equivalence between the six-position carrier and the
pair orbit.

No minimality assumption and no cardinality-seven conclusion enters
this module.
-/

namespace SevenForcingPairOrbitCardinality

noncomputable section

universe u

variable {Point : Type u}

open SevenForcingDistinctPairs
open SevenForcingPairOrbit
open SevenForcingPairOrbitNormalForm
open SevenForcingPairOrbitDistinct

/--
An explicit six-element carrier used to count the canonical pair
positions.

The nested sum has six copies of `Unit`.
-/
abbrev SixPosition :=
  Unit ⊕
    Unit ⊕
      Unit ⊕
        Unit ⊕
          Unit ⊕
            Unit

/--
Convert the explicit six-element carrier into a canonical pair
position.
-/
def sixPositionToPairPosition :
    SixPosition →
      PairPosition

  | Sum.inl _ =>
      PairPosition.base

  | Sum.inr (Sum.inl _) =>
      PairPosition.rotateOnce

  | Sum.inr (Sum.inr (Sum.inl _)) =>
      PairPosition.rotateTwice

  | Sum.inr (Sum.inr (Sum.inr (Sum.inl _))) =>
      PairPosition.reverseBase

  | Sum.inr
      (Sum.inr
        (Sum.inr
          (Sum.inr
            (Sum.inl _)))) =>
      PairPosition.reverseRotateOnce

  | Sum.inr
      (Sum.inr
        (Sum.inr
          (Sum.inr
            (Sum.inr _)))) =>
      PairPosition.reverseRotateTwice

/--
Convert a canonical pair position into the explicit six-element
carrier.
-/
def pairPositionToSixPosition :
    PairPosition →
      SixPosition

  | PairPosition.base =>
      Sum.inl ()

  | PairPosition.rotateOnce =>
      Sum.inr (Sum.inl ())

  | PairPosition.rotateTwice =>
      Sum.inr
        (Sum.inr
          (Sum.inl ()))

  | PairPosition.reverseBase =>
      Sum.inr
        (Sum.inr
          (Sum.inr
            (Sum.inl ())))

  | PairPosition.reverseRotateOnce =>
      Sum.inr
        (Sum.inr
          (Sum.inr
            (Sum.inr
              (Sum.inl ()))))

  | PairPosition.reverseRotateTwice =>
      Sum.inr
        (Sum.inr
          (Sum.inr
            (Sum.inr
              (Sum.inr ()))))

/--
The explicit six-element carrier is equivalent to the canonical
pair-position carrier.
-/
def sixPositionEquivPairPosition :
    SixPosition ≃
      PairPosition where

  toFun :=
    sixPositionToPairPosition

  invFun :=
    pairPositionToSixPosition

  left_inv := by
    intro position

    rcases position with position | position

    · cases position
      rfl

    · rcases position with position | position

      · cases position
        rfl

      · rcases position with position | position

        · cases position
          rfl

        · rcases position with position | position

          · cases position
            rfl

          · rcases position with position | position

            · cases position
              rfl

            · cases position
              rfl

  right_inv := by
    intro position
    cases position <;> rfl

/--
The ordered pair represented by a canonical position, together with
the proof that it belongs to the orbit generated by the seed.
-/
def pairAtOrbit
    (S : SevenForcing.GlobalTriadicClosure Point)
    (seed : DistinctPair (Point := Point)) :
    PairPosition →
      PairOrbit S seed

  | PairPosition.base =>
      ⟨
        pairAt S seed PairPosition.base,
        seed_mem S seed
      ⟩

  | PairPosition.rotateOnce =>
      ⟨
        pairAt S seed PairPosition.rotateOnce,
        rotate_seed_mem S seed
      ⟩

  | PairPosition.rotateTwice =>
      ⟨
        pairAt S seed PairPosition.rotateTwice,
        rotate_rotate_seed_mem S seed
      ⟩

  | PairPosition.reverseBase =>
      ⟨
        pairAt S seed PairPosition.reverseBase,
        reverse_seed_mem S seed
      ⟩

  | PairPosition.reverseRotateOnce =>
      ⟨
        pairAt S seed PairPosition.reverseRotateOnce,
        rotate_mem
          S
          seed
          (reverse seed)
          (reverse_seed_mem S seed)
      ⟩

  | PairPosition.reverseRotateTwice =>
      ⟨
        pairAt S seed PairPosition.reverseRotateTwice,
        rotate_mem
          S
          seed
          (rotate S (reverse seed))
          (
            rotate_mem
              S
              seed
              (reverse seed)
              (reverse_seed_mem S seed)
          )
      ⟩

/--
The underlying distinct pair of an orbit-valued canonical position is
the corresponding `pairAt` value.
-/
@[simp]
theorem pairAtOrbit_value
    (S : SevenForcing.GlobalTriadicClosure Point)
    (seed : DistinctPair (Point := Point))
    (position : PairPosition) :
    (pairAtOrbit S seed position).1 =
      pairAt S seed position := by

  cases position <;> rfl

/--
The map from canonical positions into the generated orbit is
injective.
-/
theorem pairAtOrbit_injective
    (S : SevenForcing.GlobalTriadicClosure Point)
    (seed : DistinctPair (Point := Point)) :
    Function.Injective
      (pairAtOrbit S seed) := by

  intro first second horbit

  apply pairAt_injective S seed

  have hvalues :
      (pairAtOrbit S seed first).1 =
        (pairAtOrbit S seed second).1 :=
    congrArg Subtype.val horbit

  rw [
    pairAtOrbit_value S seed first,
    pairAtOrbit_value S seed second
  ] at hvalues

  exact hvalues

/--
A normal-form proof supplies a canonical position representing the
given distinct pair.
-/
theorem pairNormalForm_exists_position
    (S : SevenForcing.GlobalTriadicClosure Point)
    (seed pair : DistinctPair (Point := Point))
    (hnormal : PairNormalForm S seed pair) :
    ∃ position : PairPosition,
      pairAt S seed position =
        pair := by

  cases hnormal with

  | base =>
      exact ⟨PairPosition.base, rfl⟩

  | rotateOnce =>
      exact ⟨PairPosition.rotateOnce, rfl⟩

  | rotateTwice =>
      exact ⟨PairPosition.rotateTwice, rfl⟩

  | reverseBase =>
      exact ⟨PairPosition.reverseBase, rfl⟩

  | reverseRotateOnce =>
      exact ⟨PairPosition.reverseRotateOnce, rfl⟩

  | reverseRotateTwice =>
      exact ⟨PairPosition.reverseRotateTwice, rfl⟩

/--
Every element of the generated pair orbit is represented by a
canonical position.
-/
theorem pairAtOrbit_surjective
    (S : SevenForcing.GlobalTriadicClosure Point)
    (seed : DistinctPair (Point := Point)) :
    Function.Surjective
      (pairAtOrbit S seed) := by

  intro orbitPair

  have hnormal :
      PairNormalForm S seed orbitPair.1 :=
    pairOrbit_element_has_normalForm
      S
      seed
      orbitPair

  rcases
    pairNormalForm_exists_position
      S
      seed
      orbitPair.1
      hnormal
    with ⟨position, hposition⟩

  refine ⟨position, ?_⟩

  apply Subtype.ext

  simp only [pairAtOrbit_value]
  exact hposition

/--
Canonical pair positions are equivalent to the generated pair orbit.
-/
def pairPositionEquivPairOrbit
    (S : SevenForcing.GlobalTriadicClosure Point)
    (seed : DistinctPair (Point := Point)) :
    PairPosition ≃
      PairOrbit S seed :=

  Equiv.ofBijective
    (pairAtOrbit S seed)
    ⟨
      pairAtOrbit_injective S seed,
      pairAtOrbit_surjective S seed
    ⟩

/--
The canonical pair-position carrier has natural cardinality six.
-/
theorem natCard_pairPosition :
    Nat.card PairPosition =
      6 := by

  calc
    Nat.card PairPosition =
        Nat.card SixPosition := by
      exact
        Nat.card_congr
          sixPositionEquivPairPosition.symm

    _ = 6 := by
      simp [SixPosition]

/--
Every rotation–reversal pair orbit has natural cardinality six.
-/
theorem natCard_pairOrbit
    (S : SevenForcing.GlobalTriadicClosure Point)
    (seed : DistinctPair (Point := Point)) :
    Nat.card (PairOrbit S seed) =
      6 := by

  calc
    Nat.card (PairOrbit S seed) =
        Nat.card PairPosition := by
      exact
        Nat.card_congr
          (pairPositionEquivPairOrbit S seed).symm

    _ = 6 :=
      natCard_pairPosition

end

end SevenForcingPairOrbitCardinality

#check SevenForcingPairOrbitCardinality.SixPosition
#check SevenForcingPairOrbitCardinality.sixPositionEquivPairPosition
#check SevenForcingPairOrbitCardinality.pairAtOrbit
#check SevenForcingPairOrbitCardinality.pairAtOrbit_injective
#check SevenForcingPairOrbitCardinality.pairAtOrbit_surjective
#check SevenForcingPairOrbitCardinality.pairPositionEquivPairOrbit
#check SevenForcingPairOrbitCardinality.natCard_pairPosition
#check SevenForcingPairOrbitCardinality.natCard_pairOrbit
#check SevenForcingPairOrbitCardinality.pairAtOrbit_value
#check SevenForcingPairOrbitCardinality.pairNormalForm_exists_position
