import KTLean.SevenForcingMinimality
import KTLean.Fano

/-!
# The Fano Plane as a Seven-Point Nondegenerate Witness

## Formal status

**Level 2 — Explicit finite witness.**

The existing Fano Steiner triple system on `Fin 7` is a global
triadic-closure system.

It is nondegenerate in the structural sense used by seven forcing:
the point `2` lies outside the block generated by the distinct pair
`0,1`. That generated block is the Fano line `{0,1,3}`.

Thus the Fano system supplies an explicit finite nondegenerate witness
with exactly seven points. Combined with cardinal minimality, this
removes the abstract witness assumption from the exact-cardinality
theorem.

No Fano uniqueness claim enters this module.
-/

namespace SevenForcingFanoWitness

noncomputable section

/--
The existing Fano Steiner system regarded as a global triadic-closure
system.
-/
def fanoGlobalTriadicClosure :
    SevenForcing.GlobalTriadicClosure Fano.Point :=
  Fano.system

/--
The points `0` and `1` are distinct in the Fano carrier.
-/
theorem fano_zero_ne_one :
    (0 : Fano.Point) ≠ 1 := by

  decide

/--
The point `2` lies outside the Fano block generated by `0` and `1`.
-/
theorem fano_two_not_mem_zero_one_block :
    (2 : Fano.Point) ∉
      fanoGlobalTriadicClosure.block 0 1 := by

  decide

/--
The Fano global triadic-closure system is nondegenerate.
-/
theorem fano_nondegenerate :
    SevenForcing.Nondegenerate
      fanoGlobalTriadicClosure := by

  exact
    ⟨
      0,
      1,
      2,
      fano_zero_ne_one,
      fano_two_not_mem_zero_one_block
    ⟩

/--
The Fano point carrier has exactly seven elements.
-/
theorem fano_card_eq_seven :
    Fintype.card Fano.Point =
      7 := by

  rfl

/--
The Fano plane supplies an explicit seven-point nondegenerate global
triadic-closure witness.
-/
theorem exists_seven_point_nondegenerate_witness :
    ∃
      (T :
        SevenForcing.GlobalTriadicClosure Fano.Point),
      SevenForcing.Nondegenerate T ∧
        Fintype.card Fano.Point = 7 := by

  exact
    ⟨
      fanoGlobalTriadicClosure,
      fano_nondegenerate,
      fano_card_eq_seven
    ⟩

/--
Every cardinal-minimal finite nondegenerate global triadic-closure
system has exactly seven points, using the explicit Fano witness.
-/
theorem card_eq_seven_of_cardinality_minimal
    {Point : Type}
    [Fintype Point]
    [DecidableEq Point]
    (S : SevenForcing.GlobalTriadicClosure Point)
    (hMinimal :
      SevenForcingMinimality.CardinalityMinimalNondegenerate S)
    (x : Point) :
    Fintype.card Point =
      7 := by

  exact
    SevenForcingMinimality.card_eq_seven_of_minimal_and_witness
      S
      hMinimal
      x
      fanoGlobalTriadicClosure
      fano_nondegenerate
      fano_card_eq_seven

end

end SevenForcingFanoWitness

#check SevenForcingFanoWitness.fanoGlobalTriadicClosure
#check SevenForcingFanoWitness.fano_zero_ne_one
#check SevenForcingFanoWitness.fano_two_not_mem_zero_one_block
#check SevenForcingFanoWitness.fano_nondegenerate
#check SevenForcingFanoWitness.fano_card_eq_seven
#check SevenForcingFanoWitness.exists_seven_point_nondegenerate_witness
#check SevenForcingFanoWitness.card_eq_seven_of_cardinality_minimal
