import KTLean.SevenForcingDistinctPairCardinality

/-!
# Equivalence Relation Generated by Pair Rotation and Reversal

## Formal status

**Level 2 — Consequence of global triadic closure.**

The generated rotation–reversal relation on distinct ordered pairs is
reflexive, transitive, and symmetric.

Transitivity follows directly from closure under further rotations and
reversals. Symmetry follows because both generating moves are
invertible:

* three rotations return the original pair;
* two reversals return the original pair.

This promotes pair-orbit reachability to a setoid suitable for quotient
counting. No minimality assumption or cardinality-seven conclusion
enters this module.
-/

namespace SevenForcingPairOrbitEquivalence

universe u

variable {Point : Type u}

open SevenForcingDistinctPairs
open SevenForcingPairOrbit

/--
Pair-orbit reachability is reflexive.
-/
theorem inPairOrbit_refl
    (S : SevenForcing.GlobalTriadicClosure Point)
    (pair : DistinctPair (Point := Point)) :
    InPairOrbit S pair pair := by

  exact InPairOrbit.seed_mem

/--
Pair-orbit reachability is transitive.
-/
theorem inPairOrbit_trans
    (S : SevenForcing.GlobalTriadicClosure Point)
    {first second third : DistinctPair (Point := Point)}
    (hfirstSecond : InPairOrbit S first second)
    (hsecondThird : InPairOrbit S second third) :
    InPairOrbit S first third := by

  induction hsecondThird with

  | seed_mem =>
      exact hfirstSecond

  | rotate_mem hmem inductionHypothesis =>
      exact
        InPairOrbit.rotate_mem
          inductionHypothesis

  | reverse_mem hmem inductionHypothesis =>
      exact
        InPairOrbit.reverse_mem
          inductionHypothesis

/--
Starting from one rotation of a pair, two further rotations recover the
original pair.
-/
theorem rotate_predecessor_mem
    (S : SevenForcing.GlobalTriadicClosure Point)
    (pair : DistinctPair (Point := Point)) :
    InPairOrbit S (rotate S pair) pair := by

  have htwo :
      InPairOrbit S
        (rotate S pair)
        (rotate S (rotate S (rotate S pair))) :=
    InPairOrbit.rotate_mem
      (
        InPairOrbit.rotate_mem
          InPairOrbit.seed_mem
      )

  rw [rotate_three S pair] at htwo

  exact htwo

/--
Starting from the reversal of a pair, one further reversal recovers the
original pair.
-/
theorem reverse_predecessor_mem
    (S : SevenForcing.GlobalTriadicClosure Point)
    (pair : DistinctPair (Point := Point)) :
    InPairOrbit S (reverse pair) pair := by

  have hreverse :
      InPairOrbit S
        (reverse pair)
        (reverse (reverse pair)) :=
    InPairOrbit.reverse_mem
      InPairOrbit.seed_mem

  rw [reverse_involutive pair] at hreverse

  exact hreverse

/--
Pair-orbit reachability is symmetric.
-/
theorem inPairOrbit_symm
    (S : SevenForcing.GlobalTriadicClosure Point)
    {first second : DistinctPair (Point := Point)}
    (hfirstSecond : InPairOrbit S first second) :
    InPairOrbit S second first := by

  induction hfirstSecond with

  | seed_mem =>
      exact InPairOrbit.seed_mem

  | @rotate_mem pair hmem inductionHypothesis =>
      exact
        inPairOrbit_trans
          S
          (rotate_predecessor_mem S pair)
          inductionHypothesis

  | @reverse_mem pair hmem inductionHypothesis =>
      exact
        inPairOrbit_trans
          S
          (reverse_predecessor_mem S pair)
          inductionHypothesis

/--
Rotation–reversal reachability defines an equivalence relation on the
distinct ordered-pair carrier.
-/
def pairOrbitSetoid
    (S : SevenForcing.GlobalTriadicClosure Point) :
    Setoid (DistinctPair (Point := Point)) where

  r :=
    InPairOrbit S

  iseqv := by
    constructor

    · intro pair
      exact inPairOrbit_refl S pair

    · intro first second hfirstSecond
      exact inPairOrbit_symm S hfirstSecond

    · intro first second third hfirstSecond hsecondThird
      exact
        inPairOrbit_trans
          S
          hfirstSecond
          hsecondThird

/--
Two pairs are equivalent in the pair-orbit setoid exactly when the
second is reachable from the first by rotations and reversals.
-/
theorem pairOrbitSetoid_iff
    (S : SevenForcing.GlobalTriadicClosure Point)
    (first second : DistinctPair (Point := Point)) :
    (pairOrbitSetoid S).r first second ↔
      InPairOrbit S first second := by

  rfl

end SevenForcingPairOrbitEquivalence

#check SevenForcingPairOrbitEquivalence.inPairOrbit_refl
#check SevenForcingPairOrbitEquivalence.inPairOrbit_trans
#check SevenForcingPairOrbitEquivalence.rotate_predecessor_mem
#check SevenForcingPairOrbitEquivalence.reverse_predecessor_mem
#check SevenForcingPairOrbitEquivalence.inPairOrbit_symm
#check SevenForcingPairOrbitEquivalence.pairOrbitSetoid
#check SevenForcingPairOrbitEquivalence.pairOrbitSetoid_iff
