import KTLean.SevenForcingFanoFrameCrossDistinct

/-!
# Injectivity of the Seven Canonical Fano-Frame Points

## Formal status

**Level 2 — Consequence of global triadic closure and a selected
noncollinear frame.**

A frame determines seven canonical point expressions:

    x, y, complete x y, p,
    complete x p,
    complete y p,
    complete (complete x y) p.

The preceding modules prove every required pairwise-distinctness
relation. This module packages the seven expressions into an explicit
position type and proves that distinct canonical positions determine
distinct points.

No assumption that the full carrier has seven points enters this
module. The result is an injection from a seven-position carrier into
the ambient point carrier.
-/

namespace SevenForcingFanoFrameCanonicalInjective

universe u

variable {Point : Type u}
variable [DecidableEq Point]

open SevenForcingFanoFrame
open SevenForcingFanoFrameGenerated
open SevenForcingFanoFrameCrossDistinct

/--
The seven canonical positions generated by a noncollinear frame.
-/
inductive CanonicalPosition where

  | first
  | second
  | lineThird
  | external
  | firstExternalThird
  | secondExternalThird
  | lineThirdExternalThird

  deriving DecidableEq

/--
The ambient point represented by a canonical frame position.
-/
def pointAt
    {S : SevenForcing.GlobalTriadicClosure Point}
    (frame : Frame S) :
    CanonicalPosition →
      Point

  | CanonicalPosition.first =>
      frame.first

  | CanonicalPosition.second =>
      frame.second

  | CanonicalPosition.lineThird =>
      frame.lineThird

  | CanonicalPosition.external =>
      frame.external

  | CanonicalPosition.firstExternalThird =>
      Frame.firstExternalThird frame

  | CanonicalPosition.secondExternalThird =>
      Frame.secondExternalThird frame

  | CanonicalPosition.lineThirdExternalThird =>
      Frame.lineThirdExternalThird frame

/--
The seven canonical frame positions determine pairwise distinct
ambient points.
-/
theorem pointAt_injective
    {S : SevenForcing.GlobalTriadicClosure Point}
    (frame : Frame S) :
    Function.Injective
      (pointAt frame) := by

  intro firstPosition secondPosition hpoints

  have hxy :
      frame.first ≠ frame.second :=
    frame.first_ne_second

  have hzx :
      frame.lineThird ≠ frame.first :=
    frame.lineThird_ne_first

  have hzy :
      frame.lineThird ≠ frame.second :=
    frame.lineThird_ne_second

  have hpx :
      frame.external ≠ frame.first :=
    frame.external_ne_first

  have hpy :
      frame.external ≠ frame.second :=
    frame.external_ne_second

  have hpz :
      frame.external ≠ frame.lineThird :=
    frame.external_ne_lineThird

  have hax :
      Frame.firstExternalThird frame ≠
        frame.first :=
    Frame.firstExternalThird_ne_first frame

  have hap :
      Frame.firstExternalThird frame ≠
        frame.external :=
    Frame.firstExternalThird_ne_external frame

  have hay :
      Frame.firstExternalThird frame ≠
        frame.second :=
    Frame.firstExternalThird_ne_second frame

  have haz :
      Frame.firstExternalThird frame ≠
        frame.lineThird :=
    Frame.firstExternalThird_ne_lineThird frame

  have hby :
      Frame.secondExternalThird frame ≠
        frame.second :=
    Frame.secondExternalThird_ne_second frame

  have hbp :
      Frame.secondExternalThird frame ≠
        frame.external :=
    Frame.secondExternalThird_ne_external frame

  have hbx :
      Frame.secondExternalThird frame ≠
        frame.first :=
    Frame.secondExternalThird_ne_first frame

  have hbz :
      Frame.secondExternalThird frame ≠
        frame.lineThird :=
    Frame.secondExternalThird_ne_lineThird frame

  have hcz :
      Frame.lineThirdExternalThird frame ≠
        frame.lineThird :=
    Frame.lineThirdExternalThird_ne_lineThird frame

  have hcp :
      Frame.lineThirdExternalThird frame ≠
        frame.external :=
    Frame.lineThirdExternalThird_ne_external frame

  have hcx :
      Frame.lineThirdExternalThird frame ≠
        frame.first :=
    Frame.lineThirdExternalThird_ne_first frame

  have hcy :
      Frame.lineThirdExternalThird frame ≠
        frame.second :=
    Frame.lineThirdExternalThird_ne_second frame

  have hab :
      Frame.firstExternalThird frame ≠
        Frame.secondExternalThird frame :=
    Frame.firstExternalThird_ne_secondExternalThird frame

  have hac :
      Frame.firstExternalThird frame ≠
        Frame.lineThirdExternalThird frame :=
    Frame.firstExternalThird_ne_lineThirdExternalThird frame

  have hbc :
      Frame.secondExternalThird frame ≠
        Frame.lineThirdExternalThird frame :=
    Frame.secondExternalThird_ne_lineThirdExternalThird frame

  cases firstPosition <;>
    cases secondPosition <;>
    simp_all [pointAt]

/--
Different canonical positions represent different ambient points.
-/
theorem pointAt_ne
    {S : SevenForcing.GlobalTriadicClosure Point}
    (frame : Frame S)
    {firstPosition secondPosition : CanonicalPosition}
    (hpositions :
      firstPosition ≠ secondPosition) :
    pointAt frame firstPosition ≠
      pointAt frame secondPosition := by

  intro hpoints

  apply hpositions

  exact
    pointAt_injective
      frame
      hpoints

end SevenForcingFanoFrameCanonicalInjective

#check SevenForcingFanoFrameCanonicalInjective.CanonicalPosition
#check SevenForcingFanoFrameCanonicalInjective.pointAt
#check SevenForcingFanoFrameCanonicalInjective.pointAt_injective
#check SevenForcingFanoFrameCanonicalInjective.pointAt_ne
