import Mathlib.Data.Finset.Card

/-!
# Steiner Triple Systems

This module formalizes the algebraic presentation of a
Steiner triple system.

A Steiner triple system may be represented by a completion
operation

    complete : Point → Point → Point

satisfying:

1. idempotence:
       complete x x = x

2. commutativity:
       complete x y = complete y x

3. Steiner recovery:
       complete x (complete x y) = y

For distinct points `x` and `y`, the value
`complete x y` is the unique third point completing their
Steiner block.

This algebraic presentation is equivalent to the usual
incidence formulation in which every pair of distinct
points belongs to exactly one three-element block.

The incidence equivalence will be formalized separately.
-/

universe u

namespace Steiner


/--
An algebraic Steiner triple system.

The operation `complete x y` returns the third point of
the block determined by `x` and `y`.

On the diagonal, completion fixes the point.
-/
structure TripleSystem (Point : Type u) where

  complete :
    Point → Point → Point

  complete_self :
    ∀ x : Point,
      complete x x = x

  complete_comm :
    ∀ x y : Point,
      complete x y = complete y x

  complete_left :
    ∀ x y : Point,
      complete x (complete x y) = y


namespace TripleSystem


variable {Point : Type u}
variable (S : TripleSystem Point)


/--
Diagonal completion fixes the point.
-/
@[simp]
theorem complete_self'
    (x : Point) :
    S.complete x x = x := by

  exact S.complete_self x


/--
The defining Steiner recovery identity.
-/
@[simp]
theorem complete_left'
    (x y : Point) :
    S.complete x (S.complete x y) = y := by

  exact S.complete_left x y


/--
The corresponding right-hand recovery identity.

It follows from commutativity and the defining
left-hand recovery law.
-/
@[simp]
theorem complete_right
    (x y : Point) :
    S.complete (S.complete x y) y = x := by

  calc
    S.complete (S.complete x y) y =
        S.complete y (S.complete x y) := by
          exact S.complete_comm _ _

    _ =
        S.complete y (S.complete y x) := by
          rw [S.complete_comm x y]

    _ = x := by
          exact S.complete_left y x


/--
For distinct inputs, the completion cannot equal
the left input.
-/
theorem complete_ne_left
    {x y : Point}
    (hxy : x ≠ y) :
    S.complete x y ≠ x := by

  intro h

  have hrecover :
      S.complete x (S.complete x y) = y :=
    S.complete_left x y

  rw [h, S.complete_self] at hrecover

  exact hxy hrecover


/--
For distinct inputs, the completion cannot equal
the right input.
-/
theorem complete_ne_right
    {x y : Point}
    (hxy : x ≠ y) :
    S.complete x y ≠ y := by

  have hyx :
      y ≠ x :=
    Ne.symm hxy

  have hthird :
      S.complete y x ≠ y :=
    complete_ne_left S hyx

  simpa only [S.complete_comm y x]
    using hthird


/--
For distinct inputs, the three points

    x, y, complete x y

are pairwise distinct.
-/
theorem completion_pairwise_distinct
    {x y : Point}
    (hxy : x ≠ y) :
    x ≠ y ∧
    x ≠ S.complete x y ∧
    y ≠ S.complete x y := by

  constructor

  · exact hxy

  constructor

  · exact
      Ne.symm
        (complete_ne_left S hxy)

  · exact
      Ne.symm
        (complete_ne_right S hxy)


/--
The proposition that `z` completes the pair `x,y`.
-/
def Completes
    (x y z : Point) :
    Prop :=
  z = S.complete x y


/--
Every pair has exactly one completion.
-/
theorem existsUnique_completion
    (x y : Point) :
    ∃! z : Point,
      S.Completes x y z := by

  refine
    ⟨S.complete x y, ?_, ?_⟩

  · rfl

  · intro z hz
    exact hz


/--
The finite block generated by two points.
-/
def block
    [DecidableEq Point]
    (x y : Point) :
    Finset Point :=
  {x, y, S.complete x y}


/--
The left point belongs to its generated block.
-/
@[simp]
theorem left_mem_block
    [DecidableEq Point]
    (x y : Point) :
    x ∈ S.block x y := by

  simp [block]


/--
The right point belongs to its generated block.
-/
@[simp]
theorem right_mem_block
    [DecidableEq Point]
    (x y : Point) :
    y ∈ S.block x y := by

  simp [block]


/--
The completion belongs to the generated block.
-/
@[simp]
theorem completion_mem_block
    [DecidableEq Point]
    (x y : Point) :
    S.complete x y ∈ S.block x y := by

  simp [block]


/--
A block generated by two distinct points has
exactly three elements.
-/
theorem card_block_of_ne
    [DecidableEq Point]
    {x y : Point}
    (hxy : x ≠ y) :
    (S.block x y).card = 3 := by

  have hxthird :
      x ≠ S.complete x y :=
    Ne.symm
      (complete_ne_left S hxy)

  have hythird :
      y ≠ S.complete x y :=
    Ne.symm
      (complete_ne_right S hxy)

  simp [
    block,
    hxy,
    hxthird,
    hythird
  ]


/--
The generated block is independent of the order
of its two defining points.
-/
theorem block_comm
    [DecidableEq Point]
    (x y : Point) :
    S.block x y =
      S.block y x := by

  ext z

  simp [
    block,
    S.complete_comm x y,
    or_left_comm
  ]


/--
Completing either edge of a Steiner block recovers
the remaining point.
-/
theorem block_recovery
    (x y : Point) :
    S.complete x (S.complete x y) = y ∧
    S.complete y (S.complete x y) = x := by

  constructor

  · exact S.complete_left x y

  · calc
      S.complete y (S.complete x y) =
          S.complete y (S.complete y x) := by
            rw [S.complete_comm x y]

      _ = x := by
            exact S.complete_left y x


end TripleSystem

end Steiner


#check Steiner.TripleSystem
#check Steiner.TripleSystem.complete
#check Steiner.TripleSystem.complete_self'
#check Steiner.TripleSystem.complete_left'
#check Steiner.TripleSystem.complete_right
#check Steiner.TripleSystem.complete_ne_left
#check Steiner.TripleSystem.complete_ne_right
#check Steiner.TripleSystem.completion_pairwise_distinct
#check Steiner.TripleSystem.Completes
#check Steiner.TripleSystem.existsUnique_completion
#check Steiner.TripleSystem.block
#check Steiner.TripleSystem.left_mem_block
#check Steiner.TripleSystem.right_mem_block
#check Steiner.TripleSystem.completion_mem_block
#check Steiner.TripleSystem.card_block_of_ne
#check Steiner.TripleSystem.block_comm
#check Steiner.TripleSystem.block_recovery
