import KTLean.Transition
import KTLean.Evolution
import KTLean.Reversibility
import KTLean.FluxDynamics

/-!
# Tkairos

Tkairos is the locality-constrained act of lawful state
succession already embedded in the axiom-derived transition,
evolution, and reversibility machinery of KTLean.

This module introduces no new dynamical axiom.

Instead, it:

1. names the total state step as a Tkairos system;
2. proves that Tkairos history is exactly the existing
   Peano-indexed state history;
3. proves equivalence with transition-law realizations;
4. proves equivalence with reversible evolution;
5. identifies fixed-context Flux evolution as the first
   concrete Tkairos witness.

Tkairos is therefore not an additional mechanism imposed
on Kosmoplex Theory. It is the semantic interpretation of
lawful finite succession already generated by the axioms.
-/

universe u

namespace Tkairos


/--
A Tkairos system is a total lawful successor operation on a
state space.

The total function already carries the Axiom 7 requirement
that every state possesses a defined successor.
-/
structure System
    (State : Type u) where

  step :
    State → State


namespace System


/--
Every total state function determines a Tkairos system.
-/
def ofFunction
    {State : Type u}
    (step : State → State) :
    System State where

  step :=
    step


@[simp]
theorem ofFunction_step
    {State : Type u}
    (step : State → State) :

    (ofFunction step).step =
      step := by

  rfl


/--
The transition law generated by a Tkairos step.
-/
def law
    {State : Type u}
    (T : System State) :
    TransitionLaw State :=

  graphLaw T.step


/--
The constructive realization of the transition law
generated by Tkairos.
-/
def realization
    {State : Type u}
    (T : System State) :
    Realization T.law :=

  graphRealization T.step


@[simp]
theorem realization_step
    {State : Type u}
    (T : System State) :

    T.realization.step =
      T.step := by

  rfl


/--
Every Tkairos law is total and functional.

This is not a new assumption. It follows from the fact that
Tkairos is extracted from a total state function.
-/
theorem law_totalFunctional
    {State : Type u}
    (T : System State) :

    TotalFunctional T.law := by

  exact
    graphLaw_totalFunctional
      T.step


/--
The Peano-indexed history generated by repeated Tkairos
resolution.
-/
def history
    {State : Type u}
    (T : System State)
    (initial : State) :
    Nat → State :=

  stateHistory
    T.step
    initial


@[simp]
theorem history_zero
    {State : Type u}
    (T : System State)
    (initial : State) :

    T.history initial 0 =
      initial := by

  rfl


@[simp]
theorem history_succ
    {State : Type u}
    (T : System State)
    (initial : State)
    (n : Nat) :

    T.history initial (Nat.succ n) =

      T.step
        (T.history initial n) := by

  rfl


/--
Tkairos history is definitionally the existing
Peano-indexed state history.

This theorem records the semantic equivalence explicitly.
-/
theorem history_eq_stateHistory
    {State : Type u}
    (T : System State)
    (initial : State) :

    T.history initial =

      stateHistory
        T.step
        initial := by

  rfl


/--
The history produced by the Tkairos realization is exactly
the Tkairos history.
-/
theorem realizedHistory_eq_history
    {State : Type u}
    (T : System State)
    (initial : State) :

    realizedHistory
        T.realization
        initial =

      T.history initial := by

  rfl


/--
Every adjacent pair in a Tkairos history satisfies the
transition law generated by Tkairos.
-/
theorem history_respects_law
    {State : Type u}
    (T : System State)
    (initial : State)
    (n : Nat) :

    T.law
      (T.history initial n)
      (T.history initial (Nat.succ n)) := by

  exact
    realizedHistory_respects_law
      T.realization
      initial
      n


/--
An initial state and the Tkairos successor rule determine
one unique Peano-indexed history.
-/
theorem history_unique
    {State : Type u}
    (T : System State)
    (initial : State)
    (candidate : Nat → State)
    (hzero :
      candidate 0 = initial)
    (hsucc :
      ∀ n : Nat,
        candidate (Nat.succ n) =
          T.step (candidate n)) :

    candidate =
      T.history initial := by

  exact
    stateHistory_unique
      T.step
      initial
      candidate
      hzero
      hsucc


/-
## Extraction from existing transition realizations
-/

/--
Every established realization of a transition law contains
a Tkairos system.

Tkairos is extracted from the realization's existing total
step function.
-/
def ofRealization
    {State : Type u}
    {transitionLaw : TransitionLaw State}
    (r : Realization transitionLaw) :
    System State where

  step :=
    r.step


@[simp]
theorem ofRealization_step
    {State : Type u}
    {transitionLaw : TransitionLaw State}
    (r : Realization transitionLaw) :

    (ofRealization r).step =
      r.step := by

  rfl


/--
The history of Tkairos extracted from a realization is
exactly the already-defined realized history.
-/
theorem ofRealization_history
    {State : Type u}
    {transitionLaw : TransitionLaw State}
    (r : Realization transitionLaw)
    (initial : State) :

    (ofRealization r).history initial =

      realizedHistory
        r
        initial := by

  rfl


/-
## Extraction from reversible dynamics
-/

/--
Every reversible step determines a reversible Tkairos
system through its existing forward transformation.
-/
def ofReversibleStep
    {State : Type u}
    (r : ReversibleStep State) :
    System State where

  step :=
    r.step


@[simp]
theorem ofReversibleStep_step
    {State : Type u}
    (r : ReversibleStep State) :

    (ofReversibleStep r).step =
      r.step := by

  rfl


/--
The Tkairos history extracted from a reversible step is
exactly the established reversible history.
-/
theorem ofReversibleStep_history
    {State : Type u}
    (r : ReversibleStep State)
    (initial : State) :

    (ofReversibleStep r).history initial =

      r.history initial := by

  rfl


/--
The recovery transformation of a reversible step recovers
the previous entry in its Tkairos history.
-/
theorem reversible_recovers_previous
    {State : Type u}
    (r : ReversibleStep State)
    (initial : State)
    (n : Nat) :

    r.recover
        (
          (ofReversibleStep r).history
            initial
            (Nat.succ n)
        ) =

      (ofReversibleStep r).history
        initial
        n := by

  exact
    r.history_recovers_previous
      initial
      n


/--
A reversible Tkairos step is injective.
-/
theorem reversible_step_injective
    {State : Type u}
    (r : ReversibleStep State) :

    Function.Injective
      (ofReversibleStep r).step := by

  exact
    r.step_injective


/--
A reversible Tkairos step is surjective.
-/
theorem reversible_step_surjective
    {State : Type u}
    (r : ReversibleStep State) :

    Function.Surjective
      (ofReversibleStep r).step := by

  exact
    r.step_surjective


/-
## Flux as the first concrete Tkairos witness
-/

/--
Fixing one Flux state as local context produces a concrete
Tkairos system from triadic completion.

This construction links:

- Triflux;
- dynamic zero and triadic completion;
- Axiom 7 totality;
- Peano succession;
- reversible state history.
-/
def flux
    (context : Flux) :
    System Flux where

  step :=
    fluxStep context


@[simp]
theorem flux_step
    (context : Flux) :

    (flux context).step =
      fluxStep context := by

  rfl


/--
The Tkairos law induced by a fixed Flux context is exactly
the existing Flux transition law.
-/
theorem flux_law
    (context : Flux) :

    (flux context).law =
      fluxLaw context := by

  rfl


/--
The Tkairos history induced by fixed-context Flux dynamics
is exactly the existing Flux history.
-/
theorem flux_history
    (context initial : Flux) :

    (flux context).history initial =

      fluxHistory
        context
        initial := by

  rfl


/--
A fixed-context Flux Tkairos step is involutive.
-/
theorem flux_step_involutive
    (context state : Flux) :

    (flux context).step
        (
          (flux context).step state
        ) =

      state := by

  exact
    _root_.fluxStep_involutive
      context
      state


/--
A fixed-context Flux Tkairos step is bijective.
-/
theorem flux_step_bijective
    (context : Flux) :

    Function.Injective
        (flux context).step
      ∧
    Function.Surjective
        (flux context).step := by

  exact
    _root_.fluxStep_bijective
      context


/--
Applying the same local Flux Tkairos operation to the
successor reconstructs the preceding state.
-/
theorem flux_recovers_previous
    (context initial : Flux)
    (n : Nat) :

    (flux context).step
        (
          (flux context).history
            initial
            (Nat.succ n)
        ) =

      (flux context).history
        initial
        n := by

  exact
    _root_.fluxHistory_recovers_previous
      context
      initial
      n


/--
The concrete Flux Tkairos history is the unique history
with the given initial state and fixed-context successor
rule.
-/
theorem flux_history_unique
    (context initial : Flux)
    (candidate : Nat → Flux)
    (hzero :
      candidate 0 = initial)
    (hsucc :
      ∀ n : Nat,
        candidate (Nat.succ n) =
          fluxStep context (candidate n)) :

    candidate =
      (flux context).history initial := by

  exact
    history_unique
      (flux context)
      initial
      candidate
      hzero
      hsucc


end System

end Tkairos


#check Tkairos.System
#check Tkairos.System.ofFunction
#check Tkairos.System.law
#check Tkairos.System.realization
#check Tkairos.System.law_totalFunctional
#check Tkairos.System.history
#check Tkairos.System.history_succ
#check Tkairos.System.history_eq_stateHistory
#check Tkairos.System.realizedHistory_eq_history
#check Tkairos.System.history_respects_law
#check Tkairos.System.history_unique
#check Tkairos.System.ofRealization
#check Tkairos.System.ofRealization_history
#check Tkairos.System.ofReversibleStep
#check Tkairos.System.ofReversibleStep_history
#check Tkairos.System.reversible_recovers_previous
#check Tkairos.System.reversible_step_injective
#check Tkairos.System.reversible_step_surjective
#check Tkairos.System.flux
#check Tkairos.System.flux_step
#check Tkairos.System.flux_law
#check Tkairos.System.flux_history
#check Tkairos.System.flux_step_involutive
#check Tkairos.System.flux_step_bijective
#check Tkairos.System.flux_recovers_previous
#check Tkairos.System.flux_history_unique
