import KTLean.Axioms

/-!
Canonical transition laws generated by total functions.
-/

universe u


/--
The graph of a total state-transition function.

`graphLaw step s t` holds exactly when `t` is the
state produced by applying `step` to `s`.
-/
def graphLaw {State : Type u}
    (step : State → State) :
    TransitionLaw State :=
  fun s t => step s = t


/--
Every total function realizes its own graph law.
-/
def graphRealization {State : Type u}
    (step : State → State) :
    Realization (graphLaw step) where
  step := step

  realizes := by
    intro s t
    rfl


/--
When equality of states is decidable, the graph law
of a total function has a decidable realization.
-/
def graphDecidableRealization
    {State : Type u}
    [DecidableEq State]
    (step : State → State) :
    DecidableRealization (graphLaw step) where
  step := step

  realizes := by
    intro s t
    rfl

  decideLaw := fun s t =>
    inferInstanceAs (Decidable (step s = t))


/--
The graph law of every total function is total
and functional.
-/
theorem graphLaw_totalFunctional
    {State : Type u}
    (step : State → State) :
    TotalFunctional (graphLaw step) := by
  exact realization_is_totalFunctional
    (graphRealization step).realizes


#check graphLaw
#check graphRealization
#check graphDecidableRealization
#check graphLaw_totalFunctional
